### ISSUE TITLE
docs: some links not working

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#101]
For instance, see this part of API reference: http://ned14.github.io/outcome/reference/outcome/#standardese-outcome_v2_xxx::operator==%3CT,U,V,R,S,P,N,%3E(result%3CT,U,V%3Econst&,outcome%3CR,S,P,N%3Econst&)

If I scroll down to `operator==` (I am using Firefox 57.0) it indicates that it is a link, but clicking on it does not bring me anywhere. Maybe this is because of the `&` in the link?

**Comment by foonathan** [comment]
I'll investigate and escape it if necessary.

**Comment by ned14** [comment]
Yes this problem is new. Links in the synopsis no longer match anchors in the page.

**Comment by foonathan** [comment]
I can't work on it for the next few hours, will fix it this evening

**Comment by akrzemi1** [comment]
No, it is more than just the `&`. The link on the same page to `outcome` (http://ned14.github.io/outcome/reference/outcome/#standardese-outcome_v2_xxx::outcome%3CR,S,P,NoValuePolicy%3E) also does not work.

**Comment by foonathan** [comment]
Yes, something has suddenly escaped the anchors, it wasn't standardese.

I have a fix ready that will escape all special characters with `_` and `-`, should fix it completely. Can finish it in around 2 hours.

**Comment by ned14** [comment]
As of late last night, to my knowledge all links ought to now be working.
