### ISSUE TITLE
docs: result=='hidden'

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#103]
in the API reference rather than seeing `result::operator==(result<> const&)` we are seeing `result::operator==('hidden' const&)`:
https://ned14.github.io/outcome/reference/result/#standardese-outcome_v2_xxx__detail__result_final-R-S-NoValuePolicy-__operator---T-U-V--result_final-T-U-V-const--const

**Comment by ned14** [comment]
Exactly correct.

Also, in the case of some free functions, we accept a `detail::result_final<>` which is the common base class for `result` and `outcome` i.e. the free function accepts either. How one goes about representing that in Standardese is anyone's guess.

**Comment by akrzemi1** [comment]
In case of Doxygen problems like these were solved through conditional compilation with `#ifdef`-s:

```c++
#if defined BUILDING_DOCS
  bool operator==(result const&, result const&);
#else
  // real code here:
  bool operator==(compute_type<> const&, compute_type<> const&);
#endif
```

Can't you apply a similar trick in this case?

**Comment by foonathan** [comment]
Note that in the long-term, I'd definitely fix this issue.

**Comment by ned14** [comment]
Unfortunately standardese isn't amenable to such tricks such as with doxygen because libclang expects a valid program input, and not giving it one causes large chunks of documentation to be skipped.

We'll move this to #75 and track it there.

**Comment by foonathan** [comment]
> Unfortunately standardese isn't amenable to such tricks such as with doxygen because libclang expects a valid program input

Actually, I think you can get away giving it syntactically well-formed input that isn't semantically valid. (To the extent that C++ parsing requires name lookup, of course). So if you call functions whose types don't matter, libclang doesn't care, for example.
