### ISSUE TITLE
Visual Studio 2017 version 15.5.4: Internal compiler error

### ISSUE THREAD

**Issue by svitalij** [ned14/outcome#106]
Given the following input, latest MSVC v15.5.4 fails with an internal error:
```cpp
#include "outcome.hpp" // saved single header

int main()
{
    return 0;
}
```

Build log:
> 1>OutcomeTest.cpp
> 1>e:\projects\c++\outcometest\outcometest\outcome.hpp(2464): fatal error C1001: An internal error has occurred in the compiler.
> 1>(compiler file 'msc1.cpp', line 1507)
> 1> To work around this problem, try simplifying or changing the program near the locations listed above.
> 1>Please choose the Technical Support command on the Visual C++
> 1> Help menu, or open the Technical Support help file for more information
> 1>e:\projects\c++\outcometest\outcometest\outcome.hpp(2464): note: see reference to class template instantiation 'outcome_v2_f1696316::detail::value_storage_trivial<T>' being compiled
> 1>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\CL.exe'
> 1>    Please choose the Technical Support command on the Visual C++
> 1>    Help menu, or open the Technical Support help file for more information
> 1>Done building project "OutcomeTest.vcxproj" -- FAILED.

A quick workaround is to remove /permissive- option, then the code compiles.
Looks like a problem in the compiler, not in the library. But may be you can suggest more suitable workaround.

**Comment by ned14** [comment]
2.1 now has workarounds for /permissive
