### ISSUE TITLE
Make preconditions more explicit both in docs and in the code

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#114]
Have a look at the definition of function `as_failure` if `outcome`:
```c++
  /// \output_section Converters
  /*! Returns this outcome as a `failure_type` with any errored and/or excepted state copied.
  \requires This outcome to have a failed state, else whatever `assume_error()` would do.
  */
  failure_type<error_type, exception_type> as_failure() const &
  {
    if(this->has_error() && this->has_exception())
    {
      return BOOST_OUTCOME_V2_NAMESPACE::failure(this->assume_error(), _ptr);
    }
    if(this->has_exception())
    {
      return BOOST_OUTCOME_V2_NAMESPACE::failure(error_type(), _ptr);
    }
    return BOOST_OUTCOME_V2_NAMESPACE::failure(this->assume_error(), exception_type());
  }
```
First, I recommend using Standardese's tag `\preconditions` rather than `\requires`. While the latter is in accord with C++ Standard, even the Committee people now consider introducing label *Preconditions:* so that readers can easily tell apart situations that prevent compilation from situations that cause UB.

Second, describe precondition formally:

*Preconditions:* `this->has_failure()`.

Third, do not specify what happens when the contract is violated. People should be interested in making sure that they adhere to the contract: not to what behavior they trigger if they fail.

Fourth, enforce the precondition with an assertion in function body:

```c++
assert(this->has_failure());
``` 
Or a similar tool. I know that ultimately (if `as_failure` is called with no failure) you will hit `this->assume_error()` and its precondition but this is not enough. The first source of the bug is that `as_failure` has been called out of contract, and we need to see this message, rather than that `assume_error` has been called out of contract.

**Comment by ned14** [comment]
Thing is, people may wish to have `assume_error()` do something. But otherwise I agree with everything you say. Thanks for the feedback.

**Comment by akrzemi1** [comment]
What I have seen other libraries do is to say nothing what happens when describing a function, but before all the declarations there is a statement like "all preconditions are enforced with a call to `NoValuePolicy::narrow_value_check`".

**Comment by ned14** [comment]
Now present in manually rewritten reference docs.
