### ISSUE TITLE
Initialization from `failure_type` drops default-constructed values

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#115]
The result of initializing an outcome with a default-constructed error (or exception) has different results if done directly versus through `failure_type`:

```c++
#include "outcome.hpp"
namespace out = OUTCOME_V2_NAMESPACE;

int main()
{  
    {
        out::outcome<int> o = std::error_code{};
        assert (o.has_error());
    }
    {
        out::outcome<int> o = out::failure(std::error_code{});
        assert (!o.has_error());
    }
}
```

**Comment by ned14** [comment]
I've figured out the cause: `outcome` compares the E in failure_type to default constructed editions to determine whether to set EC or EP. That's such an obvious bug. I don't know what I was thinking when I wrote that code. THANK YOU.

**Comment by ned14** [comment]
Fixed
