### ISSUE TITLE
Some implementation issues

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#127]
A number of issues in implementation I observed in review.

1. In `config.hpp`, 
```c++
#if !defined(STANDARDESE_IS_IN_THE_HOUSE) && (_HAS_CXX17 || __cplusplus >= 201700)
```
`_HAS_CXX17` is a Microsoft extension. You check its value but do not check if it is even defined.

2. Names `STANDARDESE_IS_IN_THE_HOUSE` and `DOXYGEN_IS_IN_THE_HOUSE` -- unless they are enforced by the 3rd party libraries, maybe change their names so that they start with `BOOST_OUTCOME_`?

3. In `result_storage.hpp`:
```c++
   // Used by iostream support to access state
    detail::value_storage_select_impl<_value_type> &__state() { return _state; }
    const detail::value_storage_select_impl<_value_type> &__state() const { return _state; }
``` 
Declaring names with two underscores is UB.

4. In `value_storage.hpp`: 
```c++
    constexpr void swap(value_storage_trivial &o)
    {
      // storage is trivial, so just use assignment
      using std::swap;
      swap(*this, o);
    }
```
Why not just type `std::swap(*this, o);`? You know exactly which overload you want to call.

**Comment by ned14** [comment]
All look reasonable.
