### ISSUE TITLE
Line-height eats underscores in docs

### ISSUE THREAD

**Issue by catskul** [ned14/outcome#133]
In latest chrome browser certain code blocks appear to have spaces where there should be underscores. This is because of the default line-height property in main.scss.

![selection_082](https://user-images.githubusercontent.com/375302/35835436-b80b4fd2-0aa8-11e8-8339-2991afdd60dd.png)

Resolved by editing local.css and upping the line height:

https://github.com/ned14/outcome/pull/132

**Comment by ned14** [comment]
Fixed by upgrading to latest docdock theme.
