### ISSUE TITLE
Print useful diagnostic if user attempts to construct a `result<T, T>`

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#135]
The following fails to compile with quite a long error message:

```c++
#include "outcome.hpp"
namespace out = OUTCOME_V2_NAMESPACE;

out::result<int, int> fun()
{
    return out::success(3);
}
```

I realize that using `result<T, T>` is fishy, but you seem to support it: I do not get any error when only declaring this function. Also, when I initialize the object as above, you seem to have sufficient information to know which `int` I want to initialize.

Maybe this is just a constructor overload missing?

**Comment by ned14** [comment]
No, constructing a `result<T, T>` is intentionally not possible. No constructors are available.

The type `result<T, T>` is intentionally legal however, so it can be casted to.

I'll look into some mechanism for printing a useful message if anybody ever tries to construct a `result<T,  T>`.

**Comment by akrzemi1** [comment]
> The type result<T, T> is intentionally legal however, so it can be cast to.

Out of curiosity, why is such casting relevant?

**Comment by ned14** [comment]
It's a QoI thing. So people can cast a `result<A, B>` to `result<C, C>` so long as they cast back to `result<A, B>` before use. This prevents us placing requirements or static asserts which fail when the types are the same. Indeed, there is a unit test specifically to ensure castability like this works.

In case you're wondering when this might ever occur at all, it's in metaprogramming. Having static asserts prevent `result<T, T>` makes metaprogramming with Outcome painful in some circumstances. Much better to permit the type, but let SFINAE detect no constructors exist for it.

**Comment by ned14** [comment]
I've been looking into this, and I can't figure out a way where all constructors remain disabled for `result<T, T>`, but casting through `result<T, T>` remains possible. Can you think of a way?

**Comment by akrzemi1** [comment]
I'll try to experiment with it while at home. Menawhile, you can just put an assertion in every constructor:

```c++
static_assert (!std::is_same<R, S>::value, "**** R and S cannot be the same type while constructing basic_result<R, S> ****"); 
```

It doesn't make the error message shorter, but at least the message contains the reason for failure spelled out explicitly.

**Comment by ned14** [comment]
Ah, but if no constructor ever gets instantiated due to SFINAE disable, then the static assert never fires.

I'm quite stumped. Even Concepts doesn't appear to offer a workaround, at least, as far as I can tell.

Ideally what we want is a constructor which does not appear to the type traits nor to SFINAE deducement but which will raise a static assert, or generate some other descriptive compiler warning, in this situation. It's surprisingly challenging.

**Comment by akrzemi1** [comment]
May be difficult, because without concepts you cannot sfinae-away the copy and move constructor easily. It is technically possible with more meta-programming hacks, But look: https://wandbox.org/permlink/CdnqP70LEcXarFfT

I have added an assert to the single-header source. I am satisfied with this workaround, given the constraints:

```
In file included from prog.cc:1:
./outcome.hpp:2754:11: error: no matching constructor for initialization of 'devoid<outcome_v2_38e09b99::detail::basic_result_storage<int, int, outcome_v2_38e09b99::policy::all_narrow>::disable_in_place_value_type>' (aka 'outcome_v2_38e09b99::detail::basic_result_storage<int, int, outcome_v2_38e09b99::policy::all_narrow>::disable_in_place_value_type')
        : _value(static_cast<Args &&>(args)...)
          ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~
./outcome.hpp:3109:11: note: in instantiation of function template specialization 'outcome_v2_38e09b99::detail::value_storage_trivial<outcome_v2_38e09b99::detail::basic_result_storage<int, int, outcome_v2_38e09b99::policy::all_narrow>::disable_in_place_value_type>::value_storage_trivial<int>' requested here
        : _state{_, static_cast<Args &&>(args)...}
          ^
./outcome.hpp:4950:5: note: in instantiation of function template specialization 'outcome_v2_38e09b99::detail::basic_result_storage<int, int, outcome_v2_38e09b99::policy::all_narrow>::basic_result_storage<int>' requested here
  : base{in_place_type<value_type_if_enabled>, detail::extract_value_from_success<value_type>(static_cast<success_type<T> &&>(o))}
    ^
prog.cc:6:12: note: in instantiation of function template specialization 'outcome_v2_38e09b99::basic_result<int, int, outcome_v2_38e09b99::policy::all_narrow>::basic_result<int, void>' requested here
    return out::success(3);
           ^
./outcome.hpp:3076:12: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'int' to 'const outcome_v2_38e09b99::detail::basic_result_storage<int, int, outcome_v2_38e09b99::policy::all_narrow>::disable_in_place_value_type' for 1st argument
    struct disable_in_place_value_type
           ^
./outcome.hpp:3076:12: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'int' to 'outcome_v2_38e09b99::detail::basic_result_storage<int, int, outcome_v2_38e09b99::policy::all_narrow>::disable_in_place_value_type' for 1st argument
    struct disable_in_place_value_type
           ^
./outcome.hpp:3076:12: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
./outcome.hpp:4952:5: error: static_assert failed "**** R and S cannot be the same type while constructing basic_result<R, S> ****"
    static_assert (!std::is_same<R, S>::value, "**** R and S cannot be the same type while constructing basic_result<R, S> ****");
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~
prog.cc:6:12: note: in instantiation of function template specialization 'outcome_v2_38e09b99::basic_result<int, int, outcome_v2_38e09b99::policy::all_narrow>::basic_result<int, void>' requested here
    return out::success(3);
           ^
2 errors generated.
```

**Comment by ned14** [comment]
Mmm, thing is, by rights those should SFINAE disable as well right?

**Comment by akrzemi1** [comment]
I think, I didn't understand your question.

But going back to the previous conversation, yes, if you sfinae away the constructors, the assertions are gone. The solutions to this problem are:

1. Sfinae out all current constructors based on `is_same_v<R, S>`; sfinae in a new constructor with a `static_assert`. But then you need to do the same with the base classes, because they also generate error messages

2. Sfinae out all current constructors based on `is_same_v<R, S>`; sfinae in a new *deleted* constructor. This way you do not get a custom message form assertion, but when user sees the declaration of deleted constructor (followed by a comment in the same line), he will get the message.

Also, back to your argument:

> It's a QoI thing. So people can cast a `result<A, B>` to `result<C, C>` so long as they cast back to `result<A, B>` before use. This prevents us placing requirements or static asserts which fail when the types are the same. Indeed, there is a unit test specifically to ensure castability like this works.
> 
> In case you're wondering when this might ever occur at all, it's in metaprogramming. Having static asserts prevent `result<T, T>` makes metaprogramming with Outcome painful in some circumstances. Much better to permit the type, but let SFINAE detect no constructors exist for it.

Maybe it is worth reconsidering. I have not seen an example where it is really needed, so I cannot easily evaluate the validity of the argument to keep `result<T, T>`.

**Comment by ned14** [comment]
I'm liking the option of conditionally enabling a deleted constructor. That rings it home that this doesn't work. I'll look into it. Thanks for the idea Andrzej.

**Comment by ned14** [comment]
See if you like https://wandbox.org/permlink/6GCAqZeIznKDLIZh

**Comment by akrzemi1** [comment]
Perfect! 
The comment says, "see docs". Is it really mentioned in the docs?

**Comment by ned14** [comment]
It will be. Won't be touching the docs for many months yet though, end of summer current estimate. Lots of new code to land and be tested first.
