### ISSUE TITLE
Failed to build due to the error C2338

### ISSUE THREAD

**Issue by shanshan0309** [ned14/outcome#138]
We build Outcome with VS2017 Update 5 on Windows. But it failed with error C2338. This issue is caused by develop revision [f533900](https://github.com/ned14/outcome/commit/f533900572b6b0d0938ad0733b59eaabdf4cf6ce). Could you please help take a look at this? Thanks!

**Repro steps:**
1. Open VS2017 x86 Native tools command tool
2. git clone --recursive http://www.github.com/azure/azure-iot-sdk-c D:\Outcome\src
3. cd D:\Outcome
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.16299.0 ..\src\
6. msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild

**Error information:**
The whole log file please see attachment.
[Outcome_log_x86_build .log](https://github.com/ned14/outcome/files/1866914/Outcome_log_x86_build.log)

"D:\Outcome\build_x86\All_BUILD.vcxproj" (Rebuild target) (1) ->
       "D:\Outcome\build_x86\_hl.vcxproj" (default target) (9:2) ->
       "D:\Outcome\build_x86\outcome_hl--expected-pass.vcxproj" (default target) (42:2) ->
       (ClCompile target) -> 
         D:\Outcome\src\test\expected-pass.cpp(1039): error C2338:  [D:\Outcome\build_x86\outcome_hl--expected-pass.vcxproj]

**Comment by shanshan0309** [comment]
Thanks for looking into this issue, @ned14. We are no longer hit this issue. Thanks!

**Comment by ned14** [comment]
Cool, thanks for letting me know.
