### ISSUE TITLE
Outcome failed due to the error C2440 when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [ned14/outcome#139]
We build Outcome with VS2017 Update 5 on Windows. But it failed with error C2440. This issue is caused by develop revision [cc218e8](https://github.com/ned14/outcome/commit/cc218e85c3f54ad140e8b5fbfcea530c7277ac83). Could you please help take a look at this? Thanks!

**Repro steps:**
1. Open VS2017 x86 Native tools command tool
2. git clone --recursive http://www.github.com/azure/azure-iot-sdk-c D:\Outcome\src
3. cd D:\Outcome
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.16299.0 ..\src\
6. msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild

**Error information:**
The whole log file please see attachment.
[log_x86_build.log](https://github.com/ned14/outcome/files/1950216/log_x86_build.log)
"D:\Outcome\build_x86\All_BUILD.vcxproj" (Rebuild target) (1) ->
       "D:\Outcome\build_x86\_hl.vcxproj" (default target) (11:2) ->
       "D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj" (default target) (42:2) ->
       (ClCompile target) -> 
         D:\Outcome\src\test\tests\experimental-core-result-status.cpp(94): error C2440: 'return': cannot convert from 'const system_error2::errc' to 'system_error2::status_code<system_error2::_generic_code_domain>' [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]
         D:\Outcome\src\test\tests\experimental-core-result-status.cpp(338): error C2440: 'initializing': cannot convert from 'initializer list' to 'outcome_v2_c8557f9b::basic_result<R,S,outcome_v2_c8557f9b::experimental::policy::status_code_throw<T,EC,void>>' [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]

**Comment by ned14** [comment]
Should be fixed now. Thanks for the report.

**Comment by shanshan0309** [comment]
@ned14, Thank you.
