### ISSUE TITLE
Outcome failed when build with MSVC on Windows

### ISSUE THREAD

**Issue by shanshan0309** [ned14/outcome#140]
Hi All,

For the issue https://github.com/ned14/outcome/issues/138 I reported before.  I commented that we are no longer hit this issue. It's becaues I applied a patch to work around this issue. Could you please help take a look at this? Thanks a lot!

Here is my workaround:
1. Insert definition of that macro somewhere at the top of basic_result.hpp file.
#if defined(_MSC_VER) && _MSVC_LANG >= 201703
#define WE_ARE_TARGETTING_CXX17 1
#else
#define WE_ARE_TARGETTING_CXX17 0
#endif

2. Then insert the condition as below in basic_result.hpp

https://github.com/ned14/outcome/blob/develop/include/outcome/basic_result.hpp#L351-L354 

OUTCOME_TEMPLATE(class T)
  OUTCOME_TREQUIRES(OUTCOME_TPRED(predicate::template enable_value_converting_constructor<T> **&& !WE_ARE_TARGETTING_CXX17**))
  constexpr basic_result(T &&t, value_converting_constructor_tag /*unused*/ = value_converting_constructor_tag()) noexcept(std::is_nothrow_constructible<value_type, T>::value)  // NOLINT
  : base{in_place_type<typename base::value_type>, static_cast<T &&>(t)}

Thanks,
Shanshan

**Comment by solodon4** [comment]
Hi Niall,

I'm the VC developer who was investigating this regression after adding support for reworded inheriting constructors in 15.7. While investigating the issue, I managed to create a small isolated repro for this case, which I believe represents what happens in the actual repro:

```C++
#if !defined(_MSC_VER)
#include <type_traits>
#define __is_constructible(...) std::is_constructible<__VA_ARGS__>::value
#endif

template<bool _Test, class _Ty = void> struct enable_if   {};
template<            class _Ty       > struct enable_if<true, _Ty>    { using type = _Ty; };
template<bool _Test, class _Ty = void>  using enable_if_t = typename enable_if<_Test, _Ty>::type;

template<class _Ty1, class _Ty2> struct is_same             { static const bool value = false; };
template<class _Ty1>             struct is_same<_Ty1, _Ty1> { static const bool value = true;  };

struct NoCopyConstructible
{
  NoCopyConstructible() = default;
  NoCopyConstructible(NoCopyConstructible const &) = delete;
  NoCopyConstructible(NoCopyConstructible &&) noexcept = default;
};

template <typename T>
struct base_wrapper : T
{
    using T::T;

    template <class U, typename = enable_if_t<!is_same<T, U>::value> >
    constexpr base_wrapper(U&& v, int i = 0) : T(static_cast<U&&>(v)) {} // **Important we have default argument here**
};

template <typename T>
struct wrapper : base_wrapper<T>
{
    typedef base_wrapper<T> base;
    using base::base;

    template <class U, typename = enable_if_t<__is_constructible(T, U)> >
    constexpr wrapper(U&& v) : T(static_cast<U&&>(v)) {}
};

static_assert(!__is_constructible(wrapper<NoCopyConstructible>, NoCopyConstructible const &), "Boom! Shakalaka"); // We static_assert here
```

Both Clang and GCC produce static assert on this as well, so the issue is likely in the source. It is definitely caused by the highlighted default argument, which was handled differently in C++14. I then recommended the source patch Shanshan reported to you.

**Comment by ned14** [comment]
Ok, I'll look into refactoring the implementation to handle this properly. Be aware that my time is extremely limited right now, and will remain so for approx one week after the June WG21 standards meeting. I can't guarantee I'll get to fixing this until then. Sorry.

**Comment by ned14** [comment]
FYI you guys on the MSVC compiler team may wish to look into https://github.com/ned14/outcome/issues/142, looks like your two phase lookup is buggy.

**Comment by solodon4** [comment]
Thank you! I passed the information on to the team

**Comment by ned14** [comment]
Found some time to fix this. Let me know if this now passes all green for you.
