### ISSUE TITLE
MSVC 19.14 chokes on deleted function with /permissive- enabled

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/outcome#142]
MSVC 19.14 seems to have a problem with deferring the lookup of dependent function calls if a function with the same name previously has been declared deleted. Outcome currently does this in [basic_outcome_failure_observers.hpp](https://github.com/ned14/outcome/blob/develop/include/outcome/detail/basic_outcome_failure_observers.hpp) line 40 and 63. A workaround would be to move the function definition from line 40 past the class definition (i.e. l. 68)

I've reported the compiler bug to MS over [here](https://developercommunity.visualstudio.com/content/problem/253500/two-phase-lookup-not-working-with-deleted-function.html)

**Comment by ned14** [comment]
Thanks for reporting this. We'll see if Microsoft fix their compiler first. I just pinged them about this on another bug they reported, it's linked above.

**Comment by BurningEnlightenment** [comment]
@ned14 MS closed the compiler issue stating that its not a bug 😕

**Comment by BurningEnlightenment** [comment]
Yes, MS is wrong; the standard clearly states
> 17.6.4.2 Candidate functions [temp.dep.candidate]
>
> 1 For a function call where the postfix-expression is a dependent name, the candidate functions are found using the usual lookup rules (6.4.1, 6.4.2) except that:
(1.1) — For the part of the lookup using unqualified name lookup (6.4.1), only function declarations from the template definition context are found.
(1.2) — For the part of the lookup using associated namespaces (6.4.2), only **function declarations found in** either the template definition context or **the template instantiation context are found**.

which implies that one must not evaluate the the function candidate list for a dependent name until the template is instantiated.

However, I have to admit I submitted an illformed minimal repro (the set of functions considered through `temp.dep.candidate.1.2` for fundamental types is always empty (as per `basic.lookup.argdep.2.2`)) 😞, I'll try to get the issue reopened.

**Comment by BurningEnlightenment** [comment]
[new MS issue](https://developercommunity.visualstudio.com/content/problem/308452/two-phase-lookup-not-working-with-deleted-function-1.html)

**Comment by ned14** [comment]
You may wish to explicitly mention that clang and GCC compile the code just fine. I've noticed that tends to make a bug report much more urgently acted upon. Compiler envy :)

**Comment by AndreasSchoenle** [comment]
As a temporary workaround replacing 

```
template <class S, class P> inline void basic_outcome_failure_exception_from_error(...) = delete;
```

with

```
#ifdef _MSC_VER
  template <class S, class P> inline void basic_outcome_failure_exception_from_error(...)
  {
    static_assert(false);
  }
#else
  template <class S, class P> inline void basic_outcome_failure_exception_from_error(...) = delete;
#endif

```
in basic_outcome_failure_observers.hpp allowed MSVC 15.8.9 to compile with /permissive- enabled. It probably is a really dumb thing to do, I did not think much about it - but it allowed me to re-enable /permissive- without having to remove outcome from my code. 

I am only using the following configurations:
```
namespace xxx
{
  template<class T>
  using result = boost::outcome_v2::result<T, std::error_code>;

  template<class T>
  using outcome = boost::outcome_v2::outcome<T, std::error_code, std::exception_ptr>;
}
```

**Comment by ned14** [comment]
Ok, give develop branch a try.

**Comment by AndreasSchoenle** [comment]
Thanks a lot. Current master works for me.

**Comment by ned14** [comment]
Yeah I was disappointed that they did not fold a fix into the latest VS2017 point release. Thanks for reporting the bug, we'll see if VS2019 does indeed fix this issue (and one other I reported).
