### ISSUE TITLE
Outcome failed due to the error C3668, C2259 when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [ned14/outcome#143]
Hi All,

We build Outcome with VS2017 Update 7 on Windows. But it failed with error c3668, c2259. This issue is caused by develop revision 4eb1466. Could you please help take a look at this? Thanks!

**Repro steps:**
1. Open VS2017 x86 Native tools command tool
2. git clone --recursive http://www.github.com/azure/azure-iot-sdk-c D:\Outcome\src
3. cd D:\Outcome
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src\
6. msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild

**Error information:**
The whole log file please see attachment.
[outcome_log_x86_build.log](https://github.com/ned14/outcome/files/2118466/outcome_log_x86_build.log)
d:\outcome\src\test\tests\experimental-core-result-status.cpp(96,29): error C3668:                             ^ [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]
         d:\outcome\src\test\tests\experimental-core-result-status.cpp(103,16): error C3668:  '_payload_domain::_throw_exception': method with override specifier 'override' did not override any base class methods [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]
       d:\outcome\src\test\tests\experimental-core-result-status.cpp(103,16): error C3668:   virtual void _throw_exception(const SYSTEM_ERROR2_NAMESPACE::status_code<void> &code) const override final  // NOLINT [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]
       d:\outcome\src\test\tests\experimental-core-result-status.cpp(103,16): error C3668:                ^ [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]
         d:\outcome\src\test\tests\experimental-core-result-status.cpp(110): error C2259:  '_payload_domain': cannot instantiate abstract class [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]
       d:\outcome\src\test\tests\experimental-core-result-status.cpp(110): error C2259: constexpr _payload_domain payload_domain; [D:\Outcome\build_x86\outcome_hl--experimental-core-result-status.vcxproj]

**Comment by ned14** [comment]
Ah, it's failing across the board in fact. See https://my.cdash.org/index.php?project=Boost.Outcome&date=2018-06-19

I'll get to it soon, it's due to changes made by SG14 Low Latency to `status_code` for Herb's deterministic exceptions.

**Comment by ned14** [comment]
Looks to be fixed latest commit.
