### ISSUE TITLE
Docs are inconsistent about whether there should be a "success" first enum

### ISSUE THREAD

**Issue by johnthagen** [ned14/outcome#146]
https://ned14.github.io/outcome/tutorial/result/

```cpp
enum class ConversionErrc
{
  EmptyString = 1, // 0 is never an error
  IllegalChar = 2,
  TooLong     = 3,
};
```

https://ned14.github.io/outcome/tutorial/default-actions/enums/

```cpp
  enum class err
  {
    success,   // REMEMBER it is best practice to always put "success"
    failure1,  // with value 0 as your first item in any error code
    failure2   // enum, even if you never use it.
  };
```

These both prescribe that `0` shouldn't be an error, but one does it with adding a `success` and another by starting the errors at `1`. These are subtly different, especially if you want to exhaustively check for errors. To me, if it's used within `result<t>`, the `success` case is redundant in the `enum class`. I think it would be better for `outcome` to have a single prescribed way in the docs to help new users.

Should these docs be made more consistent with one another?

**Comment by ned14** [comment]
Which form is better in your opinion?

**Comment by johnthagen** [comment]
Full disclosure, I come from a Rust `Result<T>` background and am only just now trying out Outcome.

In my opinion, `std::result<T>` already represents the "success" case itself, so it would be redundant to also put it into the `enum class`. Also, if someone wants to exhaustively match on the error cases, it seems like you wouldn't want the success case in there (if you're looking at the error type, you already haven't "succeeded").

If it's important not have to have a `0` value, then I would suggest we prescribe just *starting* the enum at `1`, rather than explicitly listing every single value after `1`. Are the values themselves basically meaningless? I would imagine if you had dozens of possible errors, that having to list out all of the numbers would be extra noise.

How about this?

```cpp
enum class ConversionErrc {
  EmptyString = 1, // 0 is never an error
  IllegalChar,
  TooLong,
};
```

I'm also curious about why `0` is prohibited? (I think Python also recommends avoiding `0` on it's `enum`s). Is it to avoid some kind of automatic conversion to `bool` `false`?

**Comment by akrzemi1** [comment]
Yes, we should definitely make the situation clear in the docs.

The motivation for omitting the value zero comes not from `outcome::result`, but from the mechanics of `std::error_code` from the Standard Library. Error code has this contextual conversion to `bool`, which only checks if the numeric value of the error code is zero. This operation is broken, but because someone may use it we have to recommend something that is least confusing. This is explained in detail in [this paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0824r1.html#issue-bool).

Because `outcome` makes use of `std::error_code` and `std::error_code` is described nowhere in detail, the docs for `outcome` also cover the usage of `std::error_code`. But we should probably make it more clear where we are describing `outcome` and where we are describing `std::error_code` and its shortcomings.

**Comment by ned14** [comment]
I should add to the above correct answer that Outcome also supports the proposed `std::error_code` replacement, detailed by (this paper)[https://wg21.link/P1028] where the value of all bits zero has no special meaning, and thus we cannot get confused. I still think it no harm to avoid the all bits zero value though.

P1028 specifically adds to `std::errc` a `success` enumerator. So I'd suggest that the Outcome docs be consistently the same i.e. all enumerations gain a success/undefined value which is all bits zero.

Is everybody in agreement with this?

**Comment by akrzemi1** [comment]
> Is everybody in agreement with this?

I am fine with this.

**Comment by johnthagen** [comment]
> Is everybody in agreement with this?

Just so I'm sure I'm understanding, we are proposing standardizing on:

```cpp
enum class ConversionErrc {
  Success,     // Always put a Success at value 0 to ensure proper
  EmptyString, // std::error_code contextual conversion to bool for errors.
  IllegalChar,
  TooLong,
};
```

To me there's the unfortunate side-effect that "exhaustive matching on error cases" is disrupted by this, but it seems like the precedent is already set and `outcome` is married to `std::error_code`, so I  am fine with this.

**Comment by akrzemi1** [comment]
I have just put a commit: https://github.com/ned14/outcome/commit/3fed7ed5aed85962b05d846d29592acb20ef1b75
Will that work?

**Comment by johnthagen** [comment]
@akrzemi1 Looks great to me, thank you.

**Comment by ned14** [comment]
@akrzemi1 Thanks for the commit, but I think you missed an important point: some error codings have no sensible success value, and it is semantically wrong to suggest that they do. For those codings, the all bits zero value should be called `undefined`, `unset`, `uninitialised`  or whatever. Can you adjust your commit to say this?

**Comment by ned14** [comment]
It's not about `error_code` or even Outcome, it's about the meaning of the user's enumeration.

Imagine function `parse()` which parses strings. It might have:

```c++
enum ParseFailure
{
  NumberTooBig,
  StringTooLong,
  UnknownSymbol
};
```

For this sort of failure enumeration, does `Success` or `Undefined` make more sense for the all bits zero value? It depends on `parse()`'s design. If `parse()` looked like this:

```c++
result<item_parsed, ParseFailure> parse(parse_input);
```
... then `Undefined`/`Uninitialised` is the better name, because `result<>` requires its `E` to be default constructible (to a value hopefully semantically meaningless). If `parse()` looked like this:

```c++
item_parsed parse(parse_input, ParseFailure &);
```
... then `Success` is the better name, because it might get written in the case of successful parse.

Does this make sense?

**Comment by ned14** [comment]
In other words, is "not failing" a success for a given function? Or is "not failing" just an undefined state in the failure enumeration?

**Comment by akrzemi1** [comment]
I only follow you up to certain point. You show two situations. In the second one you show that name "success" is a better solution. I agree. In the first one you show that name "uninitialized" would be better, and indeed it would be better than "success", but would leaving no name at all not be an even better solution?

Note that you can still value-initialize an enum to numeric value zero even if it is not given a name:

```c++
enum ParseFailure
{
  NumberTooBig = 1,
  StringTooLong,
  UnknownSymbol
};

ParseFailure e {}; // works
```

In the use case of `result<item_parsed, ParseFailure>` would there at any time be a need to spell out the name of the value-initialized state of `ParseFailure` explicitly?

**Comment by ned14** [comment]
> Note that you can still value-initialize an enum to numeric value zero even if it is not given a name:

I did not know this. I was quite surprised in fact.

I did an empirical test there with the undefined behaviour sanitiser. It would seem that an enum with no declared all bits zero state is considered valid by the sanitiser. That is unfortunate, I'd much prefer if an attempt to read a default initialised enum caused a UB trap.

I guess that gives three options here:

1. Enums should get an explicit "I am not initialised state"
2. Enums have the implicit "I am not initialised state" of all bits zero, which is created by not defining a state with all bits zero as its value.
3. Enums with an "I am not initialised" state should be deliberately initialised to an impossible value, to ensure attempts to use them are trapped by the UB sanitiser.

Which ought to be recommended in the Outcome docs?

**Comment by johnthagen** [comment]
FWIW, I'm with @akrzemi1 of using either:

```cpp
enum class MyErrc {
  Success,
  Failure1,
  Failure2,
};
```

or 

```cpp
enum MyErrc
{
  Failure1 = 1,
  Failure2,
};
```

Based on whether you want to use an explicit `Success` outside of `outcome::result<>`. He articulated my thoughts in his past several comments, so I don't have much else to add.

> That is unfortunate, I'd much prefer if an attempt to read a default initialised enum caused a UB trap.

I agree that is unfortunate, but I guess I've never even thought of typing something like `ParseFailure e {}`. I always use a fully named enum for this kind of thing.

> 3. Enums with an "I am not initialised" state should be deliberately initialised to an impossible value, to ensure attempts to use them are trapped by the UB sanitiser.

How can that be done?

**Comment by akrzemi1** [comment]
`result<>` aside, an enum can be used in two ways:

```c++
auto f() -> ParseFailure; // #1
auto g() -> std::error_code; // #2
```
In case 1 you need to have a `Success` value. In case 2 you might just return a value-initialized `std::error_code` which represents a generic success, but maybe you want to say that it is a success from your particular domain? In the latter case you may still want to define the `Success` value.

My preference would be to:
1. Go with `Success` value 0 in the examples (it may be less distracting on initial read).
2. In the `error_code` tutorial, at the end, explain that there is another option for leaving value zero out altogether and explain that you can still value-initialize such enum to value zero.

(This may require another subsection in the `error_code` tutorial only for treating value zero.)

Would that work?

**Comment by ned14** [comment]
As far as I can tell, all enumerations now have a success state.
