### ISSUE TITLE
OUTCOME_MATCH macro idea

### ISSUE THREAD

**Issue by johnthagen** [ned14/outcome#147]
I've been playing around with Outcome and I really like the direction it is headed (seems much more practical for type-safe error handling than `std::expected<T,E>`.

One of the usability challenges for using it in C++, rather than in say, Rust, is that the C++ type system doesn't enforce at compile time that the values and errors are unpacked correctly. That leaves the developer with two choices*, allow Outcome to throw an exception or hit undefined behavior. If you want to use Outcome in code where you disable exceptions (seems like a likely scenario), you're more or less left with the UB choice.

In Rust we would do [something like:](https://doc.rust-lang.org/book/first-edition/error-handling.html#the-result-type)

```rust
    match double_number("10") {
        Ok(n) => assert_eq!(n, 20),
        Err(err) => println!("Error: {:?}", err),
    }
```

Where it's guaranteed at compile time, `n` and `err` can't be accidentally misused in the wrong branch. 

Could we do something that emulates this with a macro? (This is totally a strawman just to present the concept. Someone who knows C macros better can likely tell me I'm crazy, or that there is a much better way to do this).

```cpp
OUTCOME_MATCH(double_number("10")) {
  {
     // `value` local automatically unwrapped from rslt.value();
     // `error` not in scope, so can't accidentally access. Checked at compile time.
    std::cout << value;
  } {
    // `error` local automatically unwrapped from rslt.error();
    // `value` not in scope, so can't accidentally access. Checked at compile time.
    switch (error) {
      ...
    {
  }
}
```

If such a thing were possible, this would then for a great majority of cases help avoid typos where `.value()` was called from the `error()` branch and `.error()` was called from the `value()` branch.

\* I suppose since you can customize the default actions, there are more possibilities, but those are the two straight-forward, common cases presented in the docs.

**Comment by johnthagen** [comment]
@akrzemi1 Great point. I was thinking about `result<T, E>` in this instance, rather than `outcome<T, E, EP>`.

Maybe the macro could be named `OUTCOME_RESULT_MATCH` to make that explicit, though that's a pretty long name, or a helpful compile error when you accidentally use it with `outcome<>`.

**Comment by ned14** [comment]
@akrzemi1 The only way I know of doing this in current C++ is via a visitor pattern, and that's sufficiently clunky that it probably isn't worth doing. Were you thinking of some other design pattern which is a lot better?

There were some proposals for Rust type matching before WG21, but I can't think of any progress on them since 2016. I remember Bjarne saying in a comment at EWG that doing them properly was quite challenging, and best not done until Reflection had finished being refactored, which hasn't happened yet. So matching is probably a C++ 23 ticket, at earliest.

**Comment by akrzemi1** [comment]
I guess in today's C++ it would look like:

```c++
auto double_number(std::string_view) -> result<double>;

match(
  double_number("10"),
  [&](double v) { std::cout << v; },
  [&](std::error_code ec) { std::cerr << ec; }
);
```
or as a member function:

```c++
double_number("10").match(
  [&](double v) { std::cout << v; },
  [&](std::error_code ec) { std::cerr << ec; }
);
```

But I am not really found of this idea. Remember that this would be in addition to raw `.value()` not a replacement thereof; so the potential for bugs would still remain.

My main objection though, is that you hardly ever need to use it. Typically, when receiving an error, you do not want to "handle" it in any way: you just need to forward it up the stack; and for this you would use operator `TRY`. If there is a more complicated (and rarer) control flow, I would just go with manual control flow, as this `MATCH` is unlikely to be able to handle any such case anyway.

To me, even the Rust's syntax is too clumsy.

**Comment by ned14** [comment]
Yes @akrzemi1's example is what I meant by visitor pattern, and it is definitely clunky to use in the real world. My personal opinion on this is that until C++ adds formal support for matching, it's not worth us implementing this into Outcome. But thanks for the suggestion.

**Comment by johnthagen** [comment]
@ned14 @akrzemi1 Thanks for the discussion. I would agree that it seems that the C++ language is not quite ready to do this optimally yet. I appreciate the consideration. 👍 

______________

I wanted to leave a few more comments for posterity sake, if/when this issue can be addressed in the coming years.

> Remember that this would be in addition to raw .value() not a replacement thereof; so the potential for bugs would still remain.

I think the same thing could be said of `OUTCOME_TRY` though. `OUTCOME_TRY` helps remove some boilerplate and potential typo bugs of repetitive code.

 > Typically, when receiving an error, you do not want to "handle" it in any way: you just need to forward it up the stack; and for this you would use operator TRY.

Agreed, usually you propagate up, but I see `MATCH` as a compliment to `TRY`, not a replacement. Eventually you *do* need to unwrap and handle the errors, and in that case some kind of `MATCH` would help avoid mistakes of accidentally using `value` instead of `error`, or vice versa.

> If there is a more complicated (and rarer) control flow, I would just go with manual control flow, as this MATCH is unlikely to be able to handle any such case anyway.

I'd be interested to see what you mean by this. What I was thinking was `MATCH` would just desugar to give you a `value` and `error` in two branches (just the like docs show for manual unwrapping now). I'm curious what case this doesn't help.

_______

My main motivation is that I'm trying to weigh the cost/benefits of Outcome vs exceptions, especially when teaching it to a team of developers who have no background in this kind of type-safe tagged-union error handling. Though exceptions have many issues you've elaborated well in your talks and docs, Outcome brings some potential traps to fall into as well (like the one being addressed here). Hopefully in the future we can improve the compile-time guarantees to tip the scales even further towards Outcome-style error handling.

With compile-time guarantees about `value` and `error` access, we could completely remove the need for all of the "accidental default actions", in a similar vein to how Rust works.

**Comment by ned14** [comment]
> Hopefully in the future we can improve the compile-time guarantees to tip the scales even further towards Outcome-style error handling.

So the current proposal before WG21 is to make exception throws optionally like Outcome: 

- [P0709 _Zero overhead deterministic exceptions_](https://wg21.link/P0709)
- [P1028 _SG14 status_code and standard error object_](http://wg21.link/P1028)
- [P1095 _Zero overhead deterministic failure_](https://groups.google.com/a/isocpp.org/forum/#!topic/std-proposals/HV-7y5XZmBw)

Outcome already support P1028, indeed it generates much tighter codegen with it.
