### ISSUE TITLE
`fetch` not available from commandline on macOS 10.13.6

### ISSUE THREAD

**Issue by johnthagen** [ned14/outcome#148]
The docs say:

> On BSD and OS X:
> `fetch https://github.com/ned14/outcome/raw/develop/single-header/outcome.hpp`

But at least on macOS 10.13.6, `fetch` is not a valid command line utility installed by default (neither is `wget`).

`curl` does appear to be installed (`v7.54.0`), so perhaps the macOS instructions should be updated to use `curl` instead?

**Comment by johnthagen** [comment]
The command that worked for me (due to having to follow GitHub redirects) was:

```bash
$ curl -O -J -L https://github.com/ned14/outcome/raw/develop/single-header/outcome.hpp
```

Tested on:

```bash
$ curl --version
curl 7.54.0 (x86_64-apple-darwin17.0) ...
```

**Comment by ned14** [comment]
Ah my OS X is very old due to me avoiding their new filing system. Fixed and thanks!
