### ISSUE TITLE
Specify the contract for `.value()`

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#150]
It is still unclear for me if this is a correct usage to call `r.value()` on `r` of which I know that it does not contain a value:

```c++
result<int> r = failure();
assert (!r);
r.value(); // correct or a bug?
```

The docs give me a technical answer: "it depends on the `NoValuePolicy`", But this is not satisfactory. It is not clear whether the policy only tries to cover up for my bugs, or is it that the library is giving the ability to configure `result<>` to the extent that different instances of `result` have nothing in common?

The default policy combined with default parameter of `result<>` have a very nice property. The following filesystem-like function:

```c++
auto delete_file(path p) -> result<void>;
```

Has the following interpretation. The function will attempt to delete a specified file. If for any reason it concludes that the file was not deleted, the returned value will reflect that with `r.has_value()== false`. At this point it is not specified if it is a "failure" or an "error". Only the caller will decide this. He has two options:

Option 1: not being able to delete is an error:
```c++
delete_file("file.txt").value(); // throws an exception on failure
```

Option 2: I wan to say "delete if possible, if not possible that is fine too":
```c++
(void)delete_file("file.txt"); // "try delete"
```

This is very useful. But this feature is not preserved when I change the type from using `std::error_code` to using `boost::error_code` or `system_error2::status_code` -- because the `NoValuePolicy` changes.

If this is a feature that `r.value()` throws (personally, I would like it to be), I would expect it to be preserved when I change the policy. I would accept that the type of the exception needs to change but not the fact of throwing.

Of course, for `std::error_code` the choice for the type of the exception to throw is obvious. It is less obvious for `boost::error_code` but maybe this should be configurable -- but not by policy: by a type trait, or ADL-hooked function. 

The policy could control how you report a "hard error" or "panic"-type error: throw an exception or call `abort()`, but it should not specify UB for accessing `.value()`, because if it does, it means that you cannot tell whether:

```c++
result<T, E, P> r = failure();
assert (!r);
r.value(); // correct or a bug?
```

is correct or a bug unless you know the policy. I.e. policy should change the behavior from one to the other, but not change behavior to undefined behavior.

I realize I am restarting the long discussion. But I think one thing was never discussed before (at least I never realized it). Namely, that `delete_file("file.txt").value()` may simply mean "change from outcome-like error reporting to native error reporting." Was this your intention behind throwing from `.value()`?

**Comment by ned14** [comment]
> This is very useful. But this feature is not preserved when I change the type from using std::error_code to using boost::error_code or system_error2::status_code -- because the NoValuePolicy changes.

The _default_ NoValuePolicy changes yes, but Boost's error code should have the same semantics -- but with Boost's facilities instead -- as the standard error code.

The status code situation is a bit different. Status codes' equivalence in exception throws are defined by their code domain. So Outcome simply defers to the status code used to determine what exception ought to be thrown.

> it should not specify UB for accessing .value(), because if it does, it means that you cannot tell whether [snip] is correct or a bug unless you know the policy

Correct. But I doubt it's as bad as you think. Remember in the tutorial we strongly recommend that each library typedefs into its namespace its particular edition of `result`. So, when the programmer is reading code using library A, they'll know that library A's `result` is throwing or non-throwing. It's part of that library's contract with users.

As for spontaneous use of `result`, in general people will either always specify a custom `E` type (in which case it's probably non-throwing), or they won't (in which case it's probably throwing). I appreciate that isn't ideal, but a good library needs to balance the needs of experienced users with those of newbies wetting their toes.

**Comment by akrzemi1** [comment]
> The *default* NoValuePolicy changes yes, but Boost's error code should have the same semantics -- but with Boost's facilities instead -- as the standard error code.

What do you mean by "should" here? That the user is expected to apply enough customizations so that `boost::system::error` code exposes similar behavior? That you believe that this is already the case? 

> The status code situation is a bit different. Status codes' equivalence in exception throws are defined by their code domain. So Outcome simply defers to the status code used to determine what exception ought to be thrown.

How is Outcome able to "defer" this? Is it a special NoValuePolicy? Is generic `basic_result` aware of the existence of `system_error2::status_code`?

> Correct. But I doubt it's as bad as you think. Remember in the tutorial we strongly recommend that each library typedefs into its namespace its particular edition of `result`. 

Yes.

> So, when the programmer is reading code using library A, they'll know that library A's `result` is throwing or non-throwing. It's part of that library's contract with users.

What you say is technically correct, but I still disagree because I believe this difference in contract is not easily visible:  in library A I am using:

```c++
template <typename T>
using a_result<T> = result<T, std::error_code>;
```
And I am getting used to `f().value()` idiom for changing `result<>`-like error handling into stack unwinding.

Now some library B uses:

```c++
template <typename T>
using b_result<T> = result<T, boost::system::error_code>;
```

The two `error_code`s are very similar, so I expect similarities to `a_result`, including the `f().value()` idiom, but it silently breaks in run-time. and it is difficult to predict it statically as no policy is explicitly mentioned in either `a_result` or `b_result`.

It is not fair to make the idiom work or break based on some policy or even worse, based on the type `EC` I use. Unless no such idiom was never intended? (But it is documented here: https://ned14.github.io/outcome/tutorial/outcome/inspecting/ but it is my writing, so maybe I got your intentions wrong?)

Also, this complex behavior of the default policy is the reason why users can't simply define:

```c++
basic_result<int, error_code2::status_code>; // error: third argument missing
```
The problem would not exist if the default policy just threw some exception. (Of course other problems would then arise, but that is a different story).

> As for spontaneous use of `result`, in general people will either always specify a custom `E` type (in which case it's probably non-throwing), or they won't (in which case it's probably throwing).

I do not think this conclusion is immediately visible. But what you say also means that there is no such idiom as `f().value()`: it just happens to work for a particular instantiation of template `result<>`. Right?

> I appreciate that isn't ideal, but a good library needs to balance the needs of experienced users with those of newbies wetting their toes.

I agree with this general statement about the balance. I just fail to see these needs of the newbies that are being balanced here. Do you want to spare them the trouble of bothering to learn that there even exist policies? That is fine. But you could also achieve this by providing a different policy  that always throws (if exceptions are enabled), in the worst case a different exception type than the user might have expected. (I think the previous version of Outcome did that.)

What do you thing the newbie expects? The newbie after using `result<T>` might want to start using `result<T, E>`. Should this transition be also made gentle and without surprises?

**Comment by ned14** [comment]
> What do you mean by "should" here? That the user is expected to apply enough customizations so that boost::system::error code exposes similar behavior? That you believe that this is already the case?

I assume you're aware of https://github.com/ned14/outcome/blob/develop/include/outcome/boost_result.hpp#L168? It's the same semantics as https://github.com/ned14/outcome/blob/develop/include/outcome/std_result.hpp#L55. Indeed my own test code simply typedefs between Boost and std, and for the most part it just works identically.

> How is Outcome able to "defer" this? Is it a special NoValuePolicy? Is generic basic_result aware of the existence of system_error2::status_code?

basic_result isn't aware of any specialisation. https://github.com/ned14/outcome/blob/develop/include/outcome/experimental/status_result.hpp#L55 is the no value policy for status codes. It simply asks the status code to throw whatever exception it thinks best represents it.

> The two error_codes are very similar, so I expect similarities to a_result, including the f().value() idiom, but it silently breaks in run-time. and it is difficult to predict it statically as no policy is explicitly mentioned in either a_result or b_result.

I don't know where you're getting this from. The boost error code edition performs identically to the std error code edition. Perhaps you're referring to `result`, not `boost_result` and `std_result`? `result` is typedefed to `std_result` in the standalone edition, and to `boost_result` in the Boost edition. See https://github.com/ned14/outcome/blob/develop/include/outcome/result.hpp.

If you want `result` to understand both Boost and std error codes automatically, that isn't actually hard to do. But I also didn't feel it worth doing in a C++ 14 minimum library. If we were compatible with C++ 03, then sure it would be wise.

> But you could also achieve this by providing a different policy that always throws (if exceptions are enabled), in the worst case a different exception type than the user might have expected. (I think the previous version of Outcome did that.)

I'm getting the feeling that you're looking for an always wide contract `value()`. And that's fine, but it isn't what the Boost peer review agreed to. The sometimes narrow, sometimes wide `value()` depending on `E` design choice was discussed in fair detail during the review, and once explained there was general agreement if I remember rightly. Changing it did not appear in my notes, anyway.

I'm happy to return this design decision as a mini-review to boost-dev if you feel strongly about it. boost-dev has not reviewed the changes since the review edition (changelog is at https://ned14.github.io/outcome/changelog/), and it would be better to change this now before we enter Boost in 2019.

**Comment by akrzemi1** [comment]
> I assume you're aware of ...

No, I was in fact not. This is telling me that for each popular candidate type for `EC` in `result<T, EC>` there is a header that defines a corresponding policy. This makes sense, but is not documented anywhere? 

But still I think it does not address the heart of the issue I am reporting here.

> > The two error_codes are very similar, so I expect similarities to a_result, including the f().value() idiom, but it silently breaks in run-time. and it is difficult to predict it statically as no policy is explicitly mentioned in either a_result or b_result.
>
> I don't know where you're getting this from. The boost error code edition performs identically to the std error code edition. Perhaps you're referring to `result`, not `boost_result` and `std_result`? `result` is typedefed to `std_result` in the standalone edition, and to `boost_result` in the Boost edition. See https://github.com/ned14/outcome/blob/develop/include/outcome/result.hpp.

Let me explain. I see the following situation. I am using the stand-alone version of Outcome:

```c++
out::result<T> r = std::error_code{};
r.value(); 
```

And this `.value()` works for me. Now, while still using the stand-alone version, I want to return Boost's `error_code`:

```c++
out::result<int, boost::system::error_code> q = boost::system::error_code{};
q.value(); 
```

And I get a crash. And it is quite unexpected because I just changed the `EC` to a well known type, and I know the author is aware of this type. Here is a full example: https://wandbox.org/permlink/EydAbCn92EkI5FRC

I suppose, the same problem will appear if I do it the other way around: I start with the boost version of Outcome, but in my program I have to use both `result<T, boost::system::error_code>` and result<T, std::error_code>`. Which is not unlikely.

> If you want `result` to understand both Boost and std error codes automatically, that isn't actually hard to do. But I also didn't feel it worth doing in a C++ 14 minimum library. If we were compatible with C++ 03, then sure it would be wise.

Yes, I want it to work with any type of `EC` out of the box. And I believe that with a different approach to customizations (policies) it can be easily achievable without you knowing ahead of time different possible `EC`s.

> I'm getting the feeling that you're looking for an always wide contract `value()`.

Yes, but always wide contract is only a consequence of what I am proposing, but not the core. The core is the idiom that assigns meaning to `fun().value()` which is "either successfully computed value or error reported in a 'native' way". (By 'native' I mean throw an exception, or when you are compiling w/o exceptions, call `abort()`). 

> And that's fine, but it isn't what the Boost peer review agreed to. The sometimes narrow, sometimes wide `value()` depending on `E` design choice was discussed in fair detail during the review, and once explained there was general agreement if I remember rightly. Changing it did not appear in my notes, anyway.

My recollection is quite similar. However, at the time of the review I was under the impression that calling `.value()` on a valueless result is a programmer error and the only thing we were discussing is how this programmer error must be responded to when detected at run-time. Some people are afraid of UB, so they would rather see a logic error-type exception thrown.

Since then my understanding of the library has changed and I came to believe that calling `.value()` on a valueless result is a correct thing to do and it enables the idiom "correct result or report failure in the native way". (This is reflected in the docs: we are recommending it; perhaps we shouldn't?). If I was missing this knowledge during the review, it is fair to assume that some other participants may also have been confused. 

> I'm happy to return this design decision as a mini-review to boost-dev if you feel strongly about it. boost-dev has not reviewed the changes since the review edition (changelog is at https://ned14.github.io/outcome/changelog/), and it would be better to change this now before we enter Boost in 2019.

Before we go there, I want to check if I am in consensus with you. This is my proposal, and I want to know what you think of it:

Make `fun().value()` and idiom meaning "either successfully computed value or error reported in a native way".

Maybe you already had this in mind. I am trying to determine this.

It is fair if you say that you don't want it. Then the docs at https://ned14.github.io/outcome/tutorial/outcome/inspecting/ need to be updated in order not to recommend `old::h().value()`.

**Comment by ned14** [comment]
> No, I was in fact not. This is telling me that for each popular candidate type for EC in result<T, EC> there is a header that defines a corresponding policy. This makes sense, but is not documented anywhere?

Documentation is untouched since the peer review. Lack of time due to current work contract.

> And I get a crash. And it is quite unexpected because I just changed the EC to a well known type, and I know the author is aware of this type.

In standalone Outcome, Outcome is not aware of Boost unless you include one of the headers prefixed with `boost_`. That makes sense, to avoid needless including.

> I suppose, the same problem will appear if I do it the other way around: I start with the boost version of Outcome, but in my program I have to use both result<T, boost::system::error_code> and result<T, std::error_code>`. Which is not unlikely.

Back when I implemented the post-peer-review changes, Peter Dimov had said that on C++ 11 or newer compilers, Boost's error code would be aliased to std's error code. So the code which is in there was correct at that time. That may have changed since.

> Yes, I want it to work with any type of EC out of the box. And I believe that with a different approach to customizations (policies) it can be easily achievable without you knowing ahead of time different possible ECs.

If Boost's error code is to remain forever distinct from std error code, then I have no problem changing the Boost edition to support both std and boost error codes. But we'd need to go ask somebody who knows the (long term) answer first.

> Since then my understanding of the library has changed and I came to believe that calling .value() on a valueless result is a correct thing to do and it enables the idiom "correct result or report failure in the native way". (This is reflected in the docs: we are recommending it; perhaps we shouldn't?). 

Remember what happens is a customisation point. Some code may consider reading a value for a valueless result a logic error. Other code may consider it stack unwinding a failure not handled locally. Still other code may decide that for it, reading the value on valueless result ought to mean a longjmp() to somewhere completely different.

We can recommend, but not impose. It really does depend on code base.

> If I was missing this knowledge during the review, it is fair to assume that some other participants may also have been confused.

I don't remember you misunderstanding this at the time. I'd rate you as having a very deep understanding of Outcome compared to most.

Hence I do weigh it heavily if you feel now that your understanding was not correct. Do feel free to raise this topic on boost-dev, though you may need to explain at length Outcome to them again, as probably most people have forgotten. And of course the current docs are unchanged since the review, and don't accurately reflect the post-review changes.

> Make fun().value() and idiom meaning "either successfully computed value or error reported in a native way".

I wouldn't agree with this. I would add "or the program enters UB".

You might be surprised how many users appear to be using Outcome in the misuse-is-UB use case. I'd say a majority of those who have contacted me about Outcome so far, at least. They appear to be surprisingly reticent to use error or status codes, despite my best arguing in favour of it.

**Comment by akrzemi1** [comment]
Ok, I have read the tutorial again. I have slightly changed my position, and will now argue for something less intrusive. 

It looks to me that when the user is not satisfied with using the default type for `EC` is `result<T, EC, NVP>`, it is not enough for him to only change `EC`: he is advised to also inspect `NVP` and only if he is confident the default `NVP` would work as he expects can he live with it, but most probably, he also wants to change the `NVP`. Even if he is still going with the default `NVP` he may want to spell it explicitly, in order to show to other developers that he is making his choice explicitly. And if he does spell out the type of `NVP` there is no point in using the default one: the other ones will more unambiguously (without so many branches) reflect his intentions. My point: the user should be advised to change both `EP` and `NVP` at the same time: changing only `EC` would likely be bug prone. (Maybe except for the situation, when it is changed from `std::error_code` to an enum convertible to `std::error_code`.)

Would you agree with this?

If so, I would propose the following change to the default policy only (I am describing it only for `result<>` at this point I do not know how to generalize it for `outcome<>`):

* if `EC` is `std::error_code` (or an enum convertible to it): throw `std::system_error`
* if `EC` is `std::exception_ptr`: rethrow it
* in any other case fail to compile: this forces the programmer to make an explicit decision

This failure to compile will only be visible if the user tempers with `EC`. At this point the additional responsibility of deciding on the NoValue policy seems justified.

My suggestion is motivated by the following situation. I tried to re-create the tutorial example that shows how to address the problem with filesystem dual interfaces by using:

```c++
template <class T> using fs_result = out::result<T, failure_info>;
```

Here is the full example: https://wandbox.org/permlink/iS4jUOmAIGyzEboa .

I did everything as you have said except that I forgot to define overload for `make_error_code()`. The program still compiled, and I expected that my NoValuePolicy will still provide the wide contract and `fun().value()` idiom, but silently the all-narrow policy got chosen. (It would not if I remembered to define `make_error_code()`.) It would have helped me if at the time of forming type `out::result<T, failure_info>` or instantiating it I had got a compiler error. Then I would have known what to do.

Of course if you agreed to this change the tutorial would have to undergo a rewrite; but I would volunteer to do this.

**Comment by ned14** [comment]
I've asked boost-dev for guidance on this. We'll see what they say.

**Comment by ned14** [comment]
Ok, fix implemented. Your wandbox with latest Outcome: https://wandbox.org/permlink/iS4jUOmAIGyzEboa#wandbox-resultwindow-code-body-1
