### ISSUE TITLE
Add a policy which is wide for `.value()` but narrow for `.error()` and `.exception()`

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#151]
I am the type of a user that generally prefers narrow contracts (UB on bad input), but I see the value in `foo().value()` idiom. I would like to be able to configure my `basic_result<T, EC, NVP>` so that calling `.error()` on an error-less object, or calling `.exception()` on an exception-less outcome is UB, but I can still safely use the `foo().value()` idiom or an equivalent.

This can be achieved in two ways:
1. Provide additional predefined policy that is wide for `.value()` but narrow for `.error()` and `.exception()`, and I will just use it.
2. Add another member function into the interface of `basic_result` and `basic_outcome`: 
   ```c++
   result_type const& outcome::native() const {
      if (has_value())
         return assume_value();  
      else if (has_exception())
         std::rethrow_exception(assume_exception());
      else
         outcome_throw_as_system_error_with_payload(assume_error());   
   }
   ```
   I will use this function for my "value or throw" idiom, and use `all_narrow` policy.

I think I actually like the second option slightly better, because `fun().native()` reflects my intention directly, whereas `fun().value()` might also get into the code as a result of programmer mistake (I should have checked if I have value before calling it, but I forgot, and it now accidentally looks like a correct code).

**Comment by ned14** [comment]
I've never been keen on having the typical observers have mixes of narrow and wide contracts. I think it a serious mistake in expected's design. Either the typical observers are all-wide, or all-narrow. Be consistent in design. If one wants to get narrow on an all-wide configuration, that's what the `.assume_*()` observers are for. And if people really disagree with me, they are free to define their own policy of course. But I really do think that they are simply wrong, and it is being mean and nasty for no gain to the average C++ programmer.

I don't care much for your `native()` proposal either. It assumes exception throwing, which breaks the clean separation of concerns currently in Outcome. Right now the Outcome machinery says absolutely nothing about exceptions, that's all in the policy classes. And that took lots of effort by me to make it so, I think it very important.

Re: #150 I have a change here which causes any attempt to wide-observe a result or outcome configured with a UDT to fail to compile with a useful error message. Still testing it, the lack of two phase on default MSVC is being a pain. I'll get there by end of today I'm sure.
