### ISSUE TITLE
Request an example for gcc 5

### ISSUE THREAD

**Issue by vincent-hui** [ned14/outcome#152]
`GCC 5.4.1 is highly usable so long as you don’t use Outcome in a constexpr evaluation context.` from [Prerequisites](https://ned14.github.io/outcome/requirements/)

Can an example be provided to show how to use outcome with GCC 5?

I cannot compile existing examples with GCC 5 even I add -std=c++14 in cmakelist.txt. I installed outcome via conan.

Thank a lot.

**Comment by akrzemi1** [comment]
Indeed, the first example fails to compile of 5.4.0. First, it is missing the `<utility>` header. If I add manually, this changes to another error. This can be seen in Wandbox: https://wandbox.org/permlink/k9nuGq4YN6mxfQIB
