### ISSUE TITLE
basic.hpp fails to compile on gcc-arm-non-eabi due to missing <execinfo.h>

### ISSUE THREAD

**Issue by johnthagen** [ned14/outcome#153]
Migrated from https://github.com/ned14/outcome/issues/149#issuecomment-418702293

_____________

[The FAQ states](https://ned14.github.io/outcome/faq/):

> Outcome works perfectly with C++ exceptions and RTTI globally disabled.

But when trying to compile with `-fno-exceptions` under `gcc-arm-none-eabi`, `basic.hpp` fails to compile:

```
basic.hpp:1764:10: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h>
          ^~~~~~~~~~~~
```

This seems unfortunate as Outcome is suited to be a good fit for embedded error handling. `basic.hpp` does build correctly if `-fno-exceptions` is not passed in.

`-fno-exceptions` is important for microcontrollers because it reduces binary size.

_______

Test setup:

- macOS 10.13.6

```
$ arm-none-eabi-g++ --version
arm-none-eabi-g++ (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
```

    - Installed with Homebrew: `brew cask install gcc-arm-embedded`

**Comment by ned14** [comment]
Your embedded ARM environment is not providing the <execinfo.h> header. That is a bug with it, not Outcome. I'll look into a macro to disable using it, but you should really raise the issue with your ARM toolchain provider.

**Comment by ned14** [comment]
Ok, `OUTCOME_DISABLE_EXECINFO` should get you over your issue. Let me know if it works.

**Comment by johnthagen** [comment]
@ned14 Confirmed that using `OUTCOME_DISABLE_EXECINFO` fixes the build problem on bare-metal GCC ARM.
