### ISSUE TITLE
Add page to docs on how to customise ASIO's async_result to return outcome::result<T>

### ISSUE THREAD

**Issue by ned14** [ned14/outcome#165]
https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/async_result.html

**Comment by cstratopoulos** [comment]
Just noticed this issue as I was poking through other ones. Maybe this customization is one you've done before (possibly many times!), if not here's a gist from an implementation when I was using `outcome::result` with Beast/ASIO/coroutines TS that might be helpful: https://gist.github.com/cstratopoulos/901b5cdd41d07c6ce6d83798b09ecf9b

**Comment by ned14** [comment]
Firstly thanks for the link. Very useful.

I was a little surprised that your gist compiles on first examination. But after some more study, yes it probably does.

I personally think it suffers from the lack of separation of concerns common to all ASIO based code, however ASIO's design forces people to do that, so there is no choice.

What I would like to do, with your permission, is to present in the docs a much simplified edition, and then link to your gist as a real world implementation if that is okay?

This will all go under a new documentation section "Recipes", along with any other real world use case snippets in the future.

**Comment by cstratopoulos** [comment]
Yes that's fine with me, happy to help!

I agree with your comments as well. It's been nearly a year since I wrote that implementation and it took a few moments revisiting it to remind myself how all the parts are meant to work. I think for an outcome user the most relevant/interesting parts must just be the `operator()` overloads in `outcome_result_handler`, but wow there is quite a lot going on outside of that.

**Comment by cstratopoulos** [comment]
Hi again, was just poking through the newly added ASIO recipe and wanted to share some comments:
Looks like [this line](https://github.com/ned14/outcome/blob/master/doc/src/snippets/boost-only/asio_integration.cpp#L52) needs to `move` the buffer or it will fail to compile attempting to copy the `unique_ptr`

[Here](https://github.com/ned14/outcome/blob/32f71ed0a78c83498d90da0c3c69045fbc3006ee/doc/src/content/recipes/asio-integration.md) you write

> However the default ASIO implementation appears to currently always throw exceptions from its Coroutines token implementation

which is entirely factual. I'm going to digress a bit and offer a point/suggestion with the understanding that the documentation is perfectly valid/correct as is, and that this may moreover be low-priority with Boost 1.70 deadlines looming.

So with all that said, you may or may not want to mention the [experimental::redirect_error](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/experimental__redirect_error.html) token. Its presence in the ASIO documentation is admittedly scant, appearing as a "see also" in the [coroutines overview](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/overview/core/coroutines_ts.html) and, in action, in the [chat server example](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/example/cpp17/coroutines_ts/chat_server.cpp),

```cpp
boost::system::error_code ec;
co_await timer_.async_wait(redirect_error(token, ec));
```

where it is not actually used for nontrivial error handling/control flow.

I think the presence of these alternatives, namely

- use exceptions for control flow, or
- use `redirect_error`

may actually make a nice argument in favor of using outcome. You might be able to say something like

> The default ASIO implementation always throws exceptions through its coroutine token transformation. The [`redirect_error`](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/experimental__redirect_error.html) token transformation recovers the option to use `error_code` interfaces, but it suffers from the same [drawbacks](https://ned14.github.io/outcome/motivation/error_codes/#downsides) that make pure error codes unappealing in the synchronous case. 

With `redirect_error` the obvious approaches are

-  declare one `error_code ec` at the top of a function and reuse it repeatedly
    - variables declared far from point of use
    - may forget to do `ec = {}` in the case that one function can return non-fatal non-success with error codes
- define an `error_code ec_meow` for each `async_meow`
    - potentially leaky variable scope, may accidentally do `async_woof` then check `if (ec_meow)`.

Again you might skip this addition entirely, but I think it puts outcome in a nice position alongside coroutines async code as it's worth noting that the scope-related issues above do not occur when writing "callback spaghetti" ASIO code.

**Comment by ned14** [comment]
Cool, those notes are very useful. That recipe is WiP, as you noticed the code doesn't compile yet. I'll get back to finishing it soon, maybe later today, maybe later this week. Need to resurrect Boost.Outcome first.

The last big ticket item is to script something which replaces all the stale documentation comments with the newly written ones, as I couldn't be arsed doing it manually. Otherwise we look good to go for the cutoff on the 20th.

**Comment by ned14** [comment]
Can you give https://ned14.github.io/outcome/recipes/asio-integration/ a look through, and if it's okay, I'd say this issue is closed?

**Comment by cstratopoulos** [comment]
Looks good to me! I think the warning note, referral to the ASIO slack channel, and the references to voodoo are all appropriate, nice touches :joy:

**Comment by ned14** [comment]
ASIO slack channel? I didn't know there was one. I linked to the boost-asio tag on Stackoverflow?

**Comment by cstratopoulos** [comment]
Ah yup totally right! Typo, indeed there is no such channel I'm aware of
