### ISSUE TITLE
Submodule fetching broken for older refs

### ISSUE THREAD

**Issue by cdacamar** [ned14/outcome#169]
I'm seeing
```
error: Server does not allow request for unadvertised object 3adb2737998ccd992acb117f86388ba875f36f86
Fetched in submodule path 'doc/html', but it did not contain 3adb2737998ccd992acb117f86388ba875f36f86. Direct fetching of that commit failed.
```

To repro:

```bash
$ git clone https://github.com/ned14/outcome
$ cd outcome
$ git checkout 56b03cf4919b8388b0a6abda98bb9858c644cc01
$ git submodule update --init --recursive
```

Did the `gh-pages` branch take a rebase recently?  If this is a frequent problem is there a workaround?

**Comment by ned14** [comment]
The gh-pages branch was getting fat, and consuming a lot of data. As its history is unimportant, I reset it from time to time. You can safely delete your local gh-pages branch in the doc/html subrepo, and reclone the origin gh-pages. Thanks for reporting the issue, it's always disconcerting to see git pull's fail spectacularly.
