### ISSUE TITLE
Discrepancy between documenation and implementation regarding supported GCC version

### ISSUE THREAD

**Issue by andoks** [ned14/outcome#171]
Based on the  [requirements](https://ned14.github.io/outcome/requirements/) it seems like outcome should work with GCC 5.3 [1], but when trying to compile it, the following #define triggers (line 1107):
```
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ < 6
#error Due to a bug in nested template variables parsing, Outcome does not work on GCCs earlier than v6.
#endif
```

Used outcome.hpp from master of today (2019-02-11) using the curl command in tutorial (`curl -O -J -L https://github.com/ned14/outcome/raw/master/single-header/outcome.hpp`)

Is GCC 5.3 (MinGW) supposed to work? Have I perhaps missed some defines that need to be set for this to work?

[1]: gcc output, as downloaded through Qt 5 SDK
```
$ g++ --version
g++.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ned14** [comment]
I'm not sure where you're getting from https://ned14.github.io/outcome/requirements/ that GCCs before 6.5 are supported. It clearly says "GCC 6.5 [Linux]" or better.

The `#error` trap is specifically because so many people still try to use Outcome on GCC 5 :)

**Comment by andoks** [comment]
Indeed, for some reason I seem to have confused the various clang-versions mentioned with gcc. Apologies for the noise!

**Comment by ned14** [comment]
I'll clarify that page. You're not alone to have been confused by the wording. Thanks for the report.
