### ISSUE TITLE
Trying outcome for the first time

### ISSUE THREAD

**Issue by skgbanga** [ned14/outcome#177]
Ok, so this is embarrassing, but I am trying `outcome` and got stuck on the very basic thing. 

I downloaded the `outcome.hpp` and wrote the following test program:

```
#include "outcome.hpp"
namespace outcome = OUTCOME_V2_NAMESPACE;

TEST(Outcome, Basic) {
   auto foo = [] { return outcome::success(); };
   EXPECT_TRUE(foo());
}
```

Compiling this with clang5.0 (as well as gcc 7), I get the following error:

```
error: value of type 'outcome_v2_b93403b9::success_type<void>' is not contextually convertible to 'bool'
```

embarrassing on my part, but I expected this basic thing to work. :/

**Comment by akrzemi1** [comment]
I do not think this example should ever work. `out::success()` is only used to initialize `out::outcome` or `out::result`. It is only these latter types that you should be inspecting. The minimum test case should be something like:

```c++
TEST(Outcome, outcome_created_from_success_is_contextually_converted_to_true) {
   auto foo = [] -> outcome::result<void> { return outcome::success(); };
   EXPECT_TRUE(foo());
}
```

**Comment by skgbanga** [comment]
Oh, I see.

Maybe have a clarifying line at the end of this page: https://ned14.github.io/outcome/tutorial/essential/result/?

Thanks for the quick response.

**Comment by akrzemi1** [comment]
Oh, ok, I can see why it is confusing.
