### ISSUE TITLE
Why is outcome implemented as a product type?

### ISSUE THREAD

**Issue by skgbanga** [ned14/outcome#179]
From the interface, outcome/result seem to be a sum type (either the value is present or the error is present), however it is internally implemented as a product type. (first question in FAQ)

```cpp
struct
{
  T value;
  unsigned int flags;
  EC error;
};
```

What's the reason for this?

**Comment by ned14** [comment]
https://ned14.github.io/outcome/reference/types/basic_result/#design-rationale
