### ISSUE TITLE
[[nodiscard]] attribute for failure

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/outcome#180]
Has it been considered to add the `[[nodiscard]]` attribute to either the `failure()` free function or `failure_type<>`? 

I _almost_ failed to spot a missing `return` statement due to the declarative looking style:
```cpp
if (!ptr)
{
    outcome::failure(std::error_code{errno, std::generic_category()});
}
```
Very worrying.

**Comment by akrzemi1** [comment]
This sounds like a good idea.

**Comment by ned14** [comment]
Yes, I agree. Not sure if it can reach the Boost 1.70 cutoff deadline however.

**Comment by ned14** [comment]
Fixed! Thanks for the suggestion!

**Comment by BurningEnlightenment** [comment]
@ned14 thank you for all the effort that went into this amazing project!
