### ISSUE TITLE
Outcome riddled with UB due to not using std::launder()

### ISSUE THREAD

**Issue by ned14** [ned14/outcome#185]
I was informed in the bar during the ACCU 2019 conference that Outcome is riddled with UB. I did not believe them. However, upon reading https://wg21.link/P0532, it turns out that they were correct.

Wherever there is a possibility that a const type could be in a `T`, `EC` or `EP`, one cannot use placement new and discard the return value without introducing UB. To avoid UB, one must do one of either:

1. Always use the pointer returned by placement new to access the object just placement newed.

2. Use `std::launder` on **every** access of the placement newed object.

Outcome's implementation needs to be audited for all use of placement new where the returned pointer is discarded, and fixups applied as where necessary.

**Comment by ned14** [comment]
Added a FAQ entry describing the current policy and approach to this bug, which is expected to remain open for a long time to come: https://ned14.github.io/outcome/faq/#is-outcome-riddled-with-undefined-behaviour-for-const-const-containing-and-reference-containing-types

**Comment by BurningEnlightenment** [comment]
@ned14 would you accept a patch implementing the second solution or is this deemed infeasible?

**Comment by ned14** [comment]
I didn't want to say anything about internal committee proceedings in outward facing documentation, but there is a reasonable chance that the need for `std::launder` will go away in C++ 23, as the memory model would be modified to no longer make it needed. As no compiler ever did anything with it anyway, that's no bad thing. But it also means that work done on this right now would be wasted effort. But thanks for volunteering, very kind of you.

**Comment by ned14** [comment]
As of NB comment resolution in the Belfast meeting, this problem no longer exists in the standard.

**Comment by BurningEnlightenment** [comment]
Out of personal interest: Can you link the relevant paper?

**Comment by ned14** [comment]
I've no idea what it is, I am afraid. I heard through word of mouth due to attending the meeting.

**Comment by akrzemi1** [comment]
The paper is P1971R0 ("Core Language Changes for NB Comments at the November, 2019 (Belfast) meeting"). It will show up in the post-Belfast mailing.

**Comment by Mike-Devel** [comment]
Is launder made completely unnecessary or just as far as it would have been required in boost outcome?

**Comment by ned14** [comment]
launder remains necessary for whole objects. It is no longer necessary for subobjects where you are acting from within the containing object.

i.e. Outcome no longer needs it, so the second part of your question.
