### ISSUE TITLE
documentation rendering of narrow contract list isn't correct

### ISSUE THREAD

**Issue by hazelnusse** [ned14/outcome#188]
The list here:
https://github.com/ned14/outcome/blame/develop/doc/src/content/motivation/narrow_contract.md#L94

Doesn't get rendered correctly as a list here:
https://ned14.github.io/outcome/motivation/narrow_contract/

I can't see anything obviously wrong with the .md file, so I'm not sure what the cause is. I spent about 2 minutes looking at how the documentation is converted from .md to .html before giving up -- if there is an easy command I missed, I'm happy to run it and see if I can figure out how to fix the issue.

![list_rendered_incorrectly](https://user-images.githubusercontent.com/63265/56814344-d8970300-67f3-11e9-8e0a-bb2fc71bcd91.png)

**Comment by akrzemi1** [comment]
Pure Markdown requires an empty line before the bullet list. Hopefully, this commit will fix the problem: https://github.com/ned14/outcome/commit/7e7d94bce47d810e8d0b7ad93d7011be2f027e58.

**Comment by ned14** [comment]
Looks fixed to me. Thanks for the BR!

**Comment by hazelnusse** [comment]
Awesome, thanks @akrzemi1 @ned14 !
