### ISSUE TITLE
Testing outcome from Boost 1.70 on Linux for VxWorks

### ISSUE THREAD

**Issue by dkrejsa** [ned14/outcome#190]
Hi,
I'm trying to build the outcome tests from the Boost 1.70 archive, for VxWorks.
I'm running b2 from the boost_1_70_0/status/ directory.

The source files under libs/outcome/test/tests  appear to reference boost outcome header files
using paths like this:

../libs/outcome/test/tests/comparison.cpp:35:10: fatal error: '../../include/boost/outcome/outcome.hpp' file not found
#include "../../include/boost/outcome/outcome.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
...failed clang-vxworks.compile.c++ ../bin.v2/libs/outcome/test/comparison.test/clang-vxworks/debug/cross-compile-vxworks/link-static/tests/comparison.o...
...

But there is no 'include' subdirectory in boost_1_70_0/libs/outcome/,
so those relative include paths starting with "../../include/boost/outcome/" do not work.
I tried manually adding a symlink at

cd libs/outcome
ln -s ../.. include

so that the relative include paths would wind up at the headers under boost/outcome,
but that seems to result in some weird behavior where other symlinks are automatically created and for several of them the target and the symlink are the same and the symlinked headers wind up as looping symlinks. Ick.

Note also that there are no Boost files at /usr/include ; for the cross build targeting VxWorks, the include path is set elsewhere via an --includedir=... option for b2.

I'm guessing that outcome is assuming that if the header files are not found at
boost_1_70_0/libs/outcome/include/..., they must be at  /somename/include/...  in the standard search path.
(For me they are at ${VSB_DIR)/usr/h/public/...).

I can probably find a workaround, but I wanted to bring up the problem.  I'm guessing the use of the relative symlinks is due to the different directory layout in the non-boost version of outcome.

**Comment by ned14** [comment]
To be honest, I don't think that anyone considered that people would want to run the unit tests from the Boost end user distro, so nobody raised the fact that it could never work. It works fine from the developer build, obviously, hence https://www.boost.org/development/tests/master/developer/outcome.html

This is very easy to fix, so I shall do so for Boost 1.71. Thank you for reporting the problem, I certainly would not have noticed it without your feedback!

**Comment by dkrejsa** [comment]
Thank you!

**Comment by ned14** [comment]
Fix passes unit tests. Thanks for reporting it.
