### ISSUE TITLE
ICE trying to compile `result<int, void>`

### ISSUE THREAD

**Issue by thejohnfreeman** [ned14/outcome#191]
This might be a compiler bug, but I'm trying to answer the question: can I instantiate a `result<T, void>` that never inhabits / engages the error state?

https://wandbox.org/permlink/TpftenO5EN6EhPog

**Comment by ned14** [comment]
Reported the ICE to upstream at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90534.

`result<T, void>` has an errored state of `void`. `.has_error()` will be true, `.error()` will return `void`.
