### ISSUE TITLE
Function definition duplicated between boost and standalone version

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/outcome#192]
https://github.com/ned14/outcome/blob/dd9e672c9556066768938a358be584ed2dfd4ce1/include/outcome/std_outcome.hpp#L31-L34
This function is defined by the boost and the standalone version, but do not share the same include guard which in turn leads to a symbol redefinition compile error if both versions are included in the same translation unit.

**Comment by ned14** [comment]
Nice catch. And perfect timing too, today is the cutoff for Boost 1.71. Now fixed. Thank you!
