### ISSUE TITLE
This project needs compilable examples.

### ISSUE THREAD

**Issue by aPSopt** [ned14/outcome#196]
I am reading about this lib and try to use in my real project. And receive a lot of compilation error. I dont have a lot time to review all you sources to understand if I made mistake or your library is too raw. 
You should provide simple compilable example where catch all you mind together.

**Comment by ned14** [comment]
Literally the first page of the tutorial has compiling examples on wandbox and godbolt: https://ned14.github.io/outcome/tutorial/essential/before/
