### ISSUE TITLE
Gist permalink for ASIO recipe

### ISSUE THREAD

**Issue by cstratopoulos** [ned14/outcome#204]
Sorry for the bother, just thought I better repost my PR comment about the ASIO recipe git gist permalink as an issue in case you missed it: https://github.com/ned14/outcome/pull/198#issuecomment-517679434

**Comment by cstratopoulos** [comment]
Woops, just saw https://github.com/ned14/outcome/commit/3511c42703ab00565369476b6f1c08b1d8d2576b ! 😅 Closing

**Comment by ned14** [comment]
Yeah, sorry, I've slept in accidentally each morning last week or so, so I've been getting through the open source github backlog particularly slowly. Thanks for the reminder though.
