### ISSUE TITLE
custom domain status-code example doesn't build with boost

### ISSUE THREAD

**Issue by hazelnusse** [ned14/outcome#213]
I suspect this is just an issue where the status-code copy-pasta in outcome hasn't been updated properly, though perhaps I'm missing something else.

From this page:
https://www.boost.org/doc/libs/1_72_0/libs/outcome/doc/html/experimental/worked-example/preamble.html

There is a link to
https://github.com/ned14/status-code/blob/master/doc/custom_domain_worked_example.md

Which has a link to a Wandbox example:
https://wandbox.org/permlink/aZJ4vaEPWShqrc44

If I modify this example to have:
`#include "boost/outcome/experimental/status-code/system_error2.hpp"`
and
`using namespace BOOST_OUTCOME_SYSTEM_ERROR2_NAMESPACE;`

I get a number of compilation errors, see the wandbox output here:
https://wandbox.org/permlink/aZJ4vaEPWShqrc44

**Comment by ned14** [comment]
What's happened is that the wandbox link from https://github.com/ned14/status-code/blob/master/doc/custom_domain_worked_example.md has not been updated to match the documentation page. I've fixed that.

I've changed the code at your wandbox link to match current status_code, and now it works fine: https://wandbox.org/permlink/hIULrsRsrDyXq0vp

**Comment by hazelnusse** [comment]
Thanks @ned14 !
