### ISSUE TITLE
Support non-Windows non-POSIX platforms

### ISSUE THREAD

**Issue by burnpanck** [ned14/outcome#216]
This is a follow-up to your recent fix to [status-code issue 18](https://github.com/ned14/status-code/issues/18) (thanks by the way!): Now that status-code doesn't try to provide `posix_code` anymore, outcome shouldn't expect to find it unconditionally.

**Comment by burnpanck** [comment]
Sorry, my fault - there is no resolution to that linked issue at all - it was still my solution. Let me propose a resultion to both then...

**Comment by ned14** [comment]
Can you try latest Outcome on your system please? Define the `SYSTEM_ERROR2_NOT_POSIX` macro before usage of Outcome.Experimental, in theory it should now no longer do anything requiring POSIX. If it does, let me know what.

**Comment by ned14** [comment]
Closing due to lack of timely response.

**Comment by burnpanck** [comment]
I can now confirm that the current `master` branch as of today (which includes this fix) does work in my setup, which is non-posix, non-windows. Sorry for the late answer.
