### ISSUE TITLE
C++20 removed std::is_literal_type

### ISSUE THREAD

**Issue by 215020267** [ned14/outcome#219]
**Description:**
In /std:c++17 mode, this triggers a deprecation warning in recent versions of MSVC. In /std:c++latest mode, now that microsoft/STL#380 has been merged, this will trigger an error in VS 2019 16.6 Preview 2.

 

**Reproduce steps:**
1. git clone --recursive https://github.com/ned14/outcome  D:\Outcome\src  
2. cd D:\Outcome\src
3. mkdir build_amd64
4. cd D:\Outcome\src\build_amd64
5. cmake -G "Visual Studio 15 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 .. 2>&1
6. msbuild /m /p:Platform=x64 /p:Configuration=Release ALL_BUILD.vcxproj /t:Rebuild 2>&1
 

**ErrorMessage:**
F:\gitP\ned14\outcome\test\tests\constexpr.cpp(31): error C2039: 'is_literal_type': is not a member of 'std' [F:\gitP\ned14\outcome\build_amd64\outcome_hl--constexpr.vcxproj]

**Comment by ned14** [comment]
Was this not fixed in https://github.com/ned14/outcome/issues/218?
