### ISSUE TITLE
Upload to ConanCenter

### ISSUE THREAD

**Issue by gmgunter** [ned14/outcome#229]
With your permission, I'd like to to add the most recent release of this package to [ConanCenter](https://conan.io/center/) (the main remote of the conan package manager). 

I've modified the existing conan recipe in this repo to conform to the [current guidelines](https://github.com/conan-io/conan-center-index/wiki) for adding packages, using other [header-only libraries](https://github.com/conan-io/conan-center-index/tree/master/recipes/ctre) as a template. 

My proposed recipe is [here](https://github.com/gmgunter/conan-center-index/tree/outcome-2.1.3/recipes/outcome).

**Comment by ned14** [comment]
Looks fine. Do I need to do anything?

**Comment by gmgunter** [comment]
Nope, I don't believe any action is required on your part. 

You can check out their [license agreement](https://gist.github.com/lasote/317ecbdfc8e011cc8a24c3d6cf40051f) but you won't be asked to sign it as it pertains to the contributed recipe rather than the outcome project.
