### ISSUE TITLE
Cannot use expressions involving variables named `res` within `OUTCOME_TRYX` and friends

### ISSUE THREAD

**Issue by burnpanck** [ned14/outcome#232]
The macro  `OUTCOME_TRYX(expr)` introduces a local scope with a local variable by the name of `res`. If the expression `expr` contains a reference to an outer variable named `res` as-well, the compilation fails with `use of "res" before deduction of auto` (which is better than silently referring to the wrong variable). However, `res` is too a common name to be disallowed within that macro. Maybe a mechanism similar to `OUTCOME_TRY_UNIQUE_NAME` can be used, or at least something slightly longer would probably help.

**Comment by ned14** [comment]
Fixed on the future v2.2 branch. Awaiting Boost release manager permission before can modify develop branch. Thanks for the bug report!
