### ISSUE TITLE
error C2230: could not find module 'BOOST_OUTCOME_V2_BOOST_OUTCOME_C_MODULE_NAME'

### ISSUE THREAD

**Issue by ngladitz** [ned14/outcome#251]
I run CI for some projects where I noticed failures in "Visual Studio 2019 version 16.10 Preview 2" builds.

I haven't authored the corresponding code but with Boost 1.75.0 I saw the following diagnostics:
```
include\boost-1_75\boost/outcome.hpp(32): error C2230: could not find module 'outcome_v2_0'
```

I found the corresponding issue #246 and updated to Boost 1.76.0. Now I get a new error diagnostic:
```
include\boost-1_76\boost/outcome.hpp(38): error C2230: could not find module 'BOOST_OUTCOME_V2_BOOST_OUTCOME_C_MODULE_NAME'
```

In context of the error I see I can probably work around this by defining `BOOST_OUTCOME_DISABLE_BOOST_OUTCOME_C_MODULES` for now.

**Comment by ned14** [comment]
Thanks for the BR, and sorry that this was missed during the Boost 1.76 release.
