### ISSUE TITLE
Outcome failed to build due to error C2230 C7568 C2955 C2057 on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [ned14/outcome#253]
Hi All,

Outcome failed to build due to error C2230 C7568 C2955 C2057 on windows with MSVC, this issue can be reproduced on latest version ned14/outcome@9f57231, can you help look?

**Repro steps:**
1. git clone --recursive https://github.com/ned14/outcome.git Outcome
2. Apply outcome_coroutine_lower_workaround.patch and outcome_quickcpplib.patch
3. mkdir outcome\build_amd64 && cd outcome\build_amd64
4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 .. > cmake.log
5. set _CL_=/D_HAS_DEPRECATED_IS_LITERAL_TYPE=1 /D_SILENCE_CXX17_IS_LITERAL_TYPE_DEPRECATION_WARNING /Zc:rewrittenExpressions- /Zc:externC-
6. msbuild /m /p:Platform=x64 /p:Configuration=Release ALL_BUILD.vcxproj /t:Rebuild

**Patch file:** 
[patch_file.zip](https://github.com/ned14/outcome/files/6692715/patch_file.zip)

**Build log:**
[build.log](https://github.com/ned14/outcome/files/6692723/build.log)

**Error info:**
27>F:\gitP\ned14\outcome\test\tests\../../include/outcome.hpp(32,34): error C2230: could not find module 'outcome_v2_9f572317' [F:\gitP\ned14\outcome\build_amd64\outcome_hl--constexpr.vcxproj]
27>F:\gitP\ned14\outcome\test\tests\constexpr.cpp(49,33): error C7568: argument list missing after assumed function template 'result' [F:\gitP\ned14\outcome\build_amd64\outcome_hl--constexpr.vcxproj]
27>F:\gitP\ned14\outcome\test\tests\constexpr.cpp(49,59): error C2955: 'is_literal_type': use of class template requires template argument list [F:\gitP\ned14\outcome\build_amd64\outcome_hl--constexpr.vcxproj]
27>F:\gitP\ned14\outcome\test\tests\constexpr.cpp(49,59): error C2057: expected constant expression [F:\gitP\ned14\outcome\build_amd64\outcome_hl--constexpr.vcxproj]
27>F:\gitP\ned14\outcome\test\tests\constexpr.cpp(50,33): error C7568: argument list missing after assumed function template 'outcome' [F:\gitP\ned14\outcome\build_amd64\outcome_hl--constexpr.vcxproj]

**Comment by ned14** [comment]
I think this failure only appears if C++ 20 is enabled. C++ Modules still don't work for Outcome, so I'm minded to flip the default for C++ 20 to disabled by default, opt-in enable. Sound good?

**Comment by spacelg** [comment]
@ned14 Thanks for your message, sorry for the late reply. Flip the default for C++ 20 to disabled by default sounds good. So that we can successfully build the outcome in our default mode. 

Thanks,
Lin

**Comment by ned14** [comment]
Fixed! Thanks for the BR!
