### ISSUE TITLE
checked<T,E> is not move assignable if T is not copy constructible

### ISSUE THREAD

**Issue by DiegoBaldassarMilleuno** [ned14/outcome#259]
See [godbolt.org](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEgJykrgAyeAyYAHI%2BAEaYxCCS0gAOqAqETgwe3r4BpClpjgKh4VEssfGJtpj2hQxCBEzEBFk%2BflxcVTUZ9Y0ExZExcQnSCg1NLTnttmN9YQNlQ4kAlLaoXsTI7BzmAMx4VADUGgcHAPTn5yYaAIKjxF4OB9cHJgDsFgejTI7IB2gMo0wqiSxAOYQIBwAbmIvJgXu8NG8ACImHYfZGoqw3O4PCHo94YtFXa7EgiYFhJAxkl47NwEACeSUYrDhABVUdhif9NkkIQgmAoAPrQ7xw1FIg7ETAARy8eClCnhH1ZIBAIthmPhKKJN2JXx%2BgoFSiaEAO/KF6swqLcJJ22AOS0xeoaBqNcQIEDAYHNwphVtpVjtDqdutD1zJFKpYtpDKZzDYB3Zdud90ewEwBF9oqVnxdeF%2B/0BwNB4KhfqVXEJ%2BO1WJJNwjlO%2B0bpjOZCaT9qlsvlmEVPst1o7KdxB3TmYHtI7Of1%2Bb%2BAiLILBgjL2beFhVar9Va1IbrtzzyENCmNHtHGazGtptuwqstNO1EuOjp1%2B%2B%2B%2BaPJ9NY4v/rcgZvm6rjsD4HFwwYvsSxKnAAVLsYTIN4WA0i2TKCgQxBMIQCgcpB9bko21LWrGbZsjhNxeGkRhnuOfqCmY965ugqrgpgwAYbQgqFg0gjWuCpCgThEF4ZGTbIcR8akUGXZygqZoCj%2Bg5kdcFFhMA1E/nRilBuKjHMYIrHsZx87cQQvGCPxG4TpyQmvq6x7ul%2B56WppV4cre5bijpT67jOh5uia6nOWY1r/u5QEgWBz4WNBpy4eG%2BFRmJrYSYmSm%2BXOAJksWS4Qt%2BzmQjmYFVnFDaJURyUsqlUkyjJvZyRaW6TmlB4ZQuJbLnltGQlp9promYWwjuNm%2BR%2BDmBV11rXveXngbWI3%2BaenWisKIUctNwGgbNkFmDsrj7CcFyXGGcEMAhXhIeVqHoZhBDYcmwkEc24mVUO2LoSOHgMOgSrEicJylaJl0kQxoxMSAzLRPQgr7Gh1qg8xQpYFQTBeLQmZcamjiQ5gK1Ncm%2BOcjcf2JtREBLK1EIMKgQI8hCfVSgQ6wMKlBKvDWO66mzu7EijRAHNEhiC2TP1E39DNMwcn3oNakKoHg0vJqzNaQWzHArLQnAAKy8H4HBaKQqCcG41jWJ8awbGKO08KQBCaGrpAQEgaBYLghAkOQlA0PQEmcNb/CCCIYjsFIMiCIoKjqHrOggGY%2BiGMYJuWJ0mAOBkLhfRMfiSJrQRff0pTlBIHT5OkAiZwkOcl7U%2BeDPEUx2CntQ9OMnitBXyepwIzezCUtdF9MvTl9nA9NDXCx11wKwKObmycCdZ0XWYZgIAQBBJAoIDnBhADuAB0wCEAgXjRBRcT/GSgi72gLCnOE6BSKcawENfmCnJrkg7FwGia%2BgyAAGx/0/pgJgmtNZMB2BoJgrxRDRB2q8aIOxJBmD/hoP%2BmsqBUEwOgaIpxKLAHoAAWgQMArAxBH5eGfqgNgu8EBJCSOYYKuodrwUQk9VsaEMJYSUsOR4rIRbPD%2BqyCAXFUrIPJsTCRJwdJYHoGSXcxMhHsmQeYP%2B4jJHqKkRtJGKM0byMESog4qAmQYSIMQcUwjjKiNUQxbRqNTIvgUQYoxcRvgkHMUov%2BKi1F/WkZgZGdjuZcxsipKibhiHIAANZYIYk/F%2BwozCqmQOEqJCs3Csn4uCQSc0DyjRNPDEAeAhQsFQJCHGRo8DAGYNjXGbgwkpxSRyKK9sNYcG1qQXW%2BtDYcGNpYU2091ibBeDtMwvBbZRyWCsCJIBNZcF3u/DQkg/7%2BH8K8HYAAOfwGhEH6E4JIHWdsDacF4BvDoYytArDgLAGAiAUBUKSHQOIHsLEUgefEYA7RY5ezJMQDeEBogHOiGERo9Jfa8GvmwQQAB5BgtAQVR1IFgFg8dxDwvwFKVOpSN7wqBCnChWxrYsRafrWgeBogYWIPSDwWADnoTwCwUFKwqAGGAAoAAangTA29IVxlBaHYQohxAh39vIJQagDm6A6AYIwKBE42BJdEDekAVhGNqFighoNxSmF6ZYLgrwDgEIAOpiFoPqg1QJrr6qZOgQwPx9WQutg3TufgICuHLh0EIcwC5DGLqkUumRW6TDyL66unq%2B4dEdU3GYbqO6Rt6GPQu4ao0BraCPHu8wE1TxnsHG2Up8XNK1vs%2BFXTVBrL/gQv%2BkhRzIF%2BO0Xe9EIA9KsEnA4rtTFDM/vxDwLz6Cgl2JPUZdsLlOzua8p5197k9pAO8rgny6DfN%2Bf8%2BFgLmAUt5eCxgBBoWwoOYi5FWx9ZosbngTFBycXIDxbywlBz5XkspRgfdoziB0oZXwZlbKOVcp5dwXgwrA6CukMK8OYr4W6FjlKhO2q5WksVWTA2vIMhqo1cBLVTaLC6oOMc6oR7nAuozsmvQHre7jz0FXDI0bSNFFDcR8NWGnXd2jRG7oMx43etTQx5jVGM2rAGewWO6FMB5vVgW9pBzi2lvLZW4A1bQKzPrY26w/FW0kHbbHSWI6e0qaWAO8ZkyQB/1k2YV4XB5mLOWa8aQLS9mkHpZrDQImi1HNsHoM59tLk3KfkkChY71OsawW7OufK/3BwA7IIDkd9b8bzaQbeGEkgvpaW0jpvAumQooZ5iEqBDglrLRWqtNbZMHAbT53tVstM20HQ7JAHmvMUGeROoYsc/OmJjoFgVwW%2BVhZpbm3lMWmBxe/UJ1phbOmcFS2vChhisvidy1J/LdbCtdvqyVnYZgysuYmaQYhTBSGUEG1ZmzdmkuHI4Mc5zg7dOSDWbvbO/hNYQI0Mgr%2B/g/6vBzi0nYw3kuOfW4NkZ9mRsnfKzp0gpSflp0kEAA)

**Comment by DiegoBaldassarMilleuno** [comment]
Proposed fix:
```diff
  template <class Base> struct value_storage_delete_copy_constructor : Base  // NOLINT
  {
    using Base::Base;
    using value_type = typename Base::value_type;
    using error_type = typename Base::error_type;
    value_storage_delete_copy_constructor() = default;
    value_storage_delete_copy_constructor(const value_storage_delete_copy_constructor &) = delete;
    value_storage_delete_copy_constructor(value_storage_delete_copy_constructor &&) = default;  // NOLINT
+     value_storage_delete_copy_constructor &operator=(const value_storage_delete_copy_constructor &o) = default;
+     value_storage_delete_copy_constructor &operator=(value_storage_delete_copy_constructor &&o) = default;  // NOLINT
  };
```

`value_storage_delete_move_constructor` may need some love too...

**Comment by DiegoBaldassarMilleuno** [comment]
Copy assignment is also problematic: [godbolt.org](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEgJykrgAyeAyYAHI%2BAEaYxCCS0gAOqAqETgwe3r4BpClpjgKh4VEssfGJtpj2hQxCBEzEBFk%2BflxcVTUZ9Y0ExZExcQnSCg1NLTnttmN9YQNlQ4kAlLaoXsTI7BzmAMx4VADUGgcHAPTn5yYaAIKjxF4OB9cHJgDsFgejTI7IB2gMo0wqiSxAOYQIBwAbmIvJgXu8NG8ACImHYfZGoqw3O4PCHo94YtFXa7EgiYFhJAxkl47NwEACeSUYrDhABVUdhif9NkkIQgmAoAPrQ7xw1FIg7ETAARy8eClCnhH1ZIBAIthmPhKKJN2JXx%2BgoFSiaEAO/KF6swqLcJJ22AOS0xeoaBqNcQIEDAYHNwphVtpVjtDqdutD1zJFKpYtpDKZzDYB3Zdud90ewEwBF9oqVnxdeF%2B/0BwNB4KhfqVXEJ%2BO1WJJNwjlO%2B0bpjOZCaT9qlsvlmEVPst1o7KdxB3TmYHtI7Of1%2Bb%2BAiLILBgjL2beFhVar9Va1IbrtzzyENCmNHtHGazGtptuwqstNO1EuOjp1%2B%2B%2B%2BaPJ9NY4v/rcgZvm6rjsD4HFwwYvsSxKnAAVLsYTIN4WA0i2TKCgQxBMIQCgcpB9bko21LWrGbZsjhNxeGkRhnuOfqCmY965ugqrgpgwAYbQgqFg0gjWuCpCgThEF4ZGTbIcR8akUGXZygqZoCj%2Bg5kdcFFhMA1E/nRilBuKjHMYIrHsZx87cQQvGCPxG4TpyQmvq6x7ul%2B56WppV4cre5bijpT67jOh5uia6nOWY1r/u5QEgWBz4WNBpy4eG%2BFRmJrYSYmSm%2BXOAJksWS4Qt%2BzmQjmYFVnFDaJURyUsqlUkyjJvZyRaW6TmlB4ZQuJbLnltGQlp9promYWwjuNm%2BR%2BDmBV11rXveXngbWI3%2BaenWisKIUctNwGgbNkFmDsrj7CcFyXGGcEMAhXhIeVqHoZhBDYcmwkEc24mVUO2LoSOHgMOgSrEicJylaJl0kQxoxMSAzLRPQgr7Gh1qg8xQpYFQTBeLQmZcamjiQ5gK1Ncm%2BOcjcf2JtREBLK1EIMKgQI8hCfVSgQ6wMKlBKvDWO66mzu7EijRAHNEhiC2TP1E39DNMwcn3oNakKoHg0vJqzNaQWzHArLQnAAKy8H4HBaKQqCcG41jWJ8awbGKO08KQBCaGrpAQEgaBYLghAkOQlA0PQEmcNb/CCCIYjsFIMiCIoKjqHrOggGY%2BiGMYJuWJ0mAOBkLhfRMfiax0IRzKU5QSLH%2BTpAImcgNneSpCXDD9PnQxcLHdgp7UPTjJ4rTlx0TepwIrezCUgzxA30y9GXFdfE0teD4XKwKObmycCdZ0XWYZgIAQBBJAoIDnBhADuAB0wCEAgXjRBRcT/GSggH2gLCnOE6BSKcawEHfmCnJrkg7FwGia%2BgyAABsgCf6YCYJrTWTAdgaCYK8UQ0QdqvGiDsSQZhAEaEAZrKgVBMDoGiKcSiwB6AAFoEBgKwMQF%2BXg36oDYAfBASQkjmGCrqHa8FEJPVbGhDCWElLDkeKyEWzw/qsggFxVKaDybE2kScHSSMUZo13MTUR7I0HmEAVImRWjZEbXkajUyL5lHqIOKgJkGEiDEHFGI4yEiNEMT0YowxIjjGmLiN8EgVjVGAPUZov6cjqgZn9LWYqYYVJUTcGQ5AABrXBDFX7v2FGYVUyBIkxIVm4Vk/FwSCTmgeUaJp4YgDwEKNASR6QfjwMAZg2NcZuAiSnNJHIor2w1hwbWpBdb60NhwY2lhTZz3WJsF4O0zC8FtlHJYKwomdwPl/DQkhAH%2BH8K8HYAAOfwGgUH6E4JIHWdsDacF4NvDo4ytArDgLAGAiAUC0KSHQOIHtrEUnufEYA7RY5ezJMQbeEBoj7OiGERo9Jfa8DvmwQQAB5BgtBgVR1IFgFg8dxBwvwFKVOkJez7KBCnahWxrYsVafrWgeBogYWIPSDwWB9noTwCwEFKwqAGGAAoAAangTAe8IVxhBaHYQohxAh39vIJQah9m6A6AYIwKBE42GJdEbekAVimNqNvDgxDQbilMH0ywXBXgHGIQAdTELQfVBqgTXX1UydAhgfj6ohdbbutR07uHbpMIIX0p4LCHpXAoGQy4dGLrUT1Bcu4BJ7nUGY/rk7hr7sG%2BuI827ZDaAm/u8wQ2z3nsHG2Uo8UtK1nsuF3TVCrMAcQwBkhRzIF%2BO0A%2B9EIC9KsEnA4rsLHDJ/vxDwzz6Cgl2FwJYYy7bnKdrcl5jy753O7SAN5w9PlxB%2BX8uFALmDkp5WCxgBAoUwv2QipFWx9aoubngDFqr9bYuQLinlBL9lyrJRSjAe6xnEFpfSvgTLWXss5dy7gvAhWBwFdIIV4dRVwt0LHSVCdtWypJQqsmBteQZFVeqggCskRasbRYXVBwjlhqdRAVwUbc4Dy9XoQNfrXXJtI0UPO09Q1dF7pG8jehHXdBmHG71E9miMa7qx6jxG%2B2rEGewWO6FMC5vVvmjp%2Byi0lrLRW4AVbQJcFrQcetMr%2BItpIG22OksR3dq0/2m2g6pkgEAUp1erwuBzIWUs140hWm7NIHSzWGhJOFsObYPQpz7YXOua/JI1Cx26fjbgt23rf38uDgB2QQHI76xE7m0ge8MJJBfa09pnTeDdIhdQ/zEJUCHGLaW8tlbq1mZU52idcQ219oHRMh2SA/MBYoE8yr8RY4hYsTHXlf7Iu8pi9SnNPKktMBS9%2B8TbSC1dM4Nlze1CTEFZk8V%2BTpXlP1qCz2kZBmvOTNIGQpgFDKDjYc05lzGWDkcCOZ5ozpBpmSFWQfSQmt/Ca2gRoNBv9/CANeJrbZHAdiTcy%2B57b43RmuamxdwzEyVgYu%2BWnSQQA)

The following would seem to fix it:
```diff
  using value_storage_select_move_assignment =
  std::conditional_t<std::is_trivially_move_assignable<devoid<T>>::value && std::is_trivially_move_assignable<devoid<E>>::value,
                     value_storage_select_copy_constructor<T, E>,
                     std::conditional_t<std::is_move_assignable<devoid<T>>::value && std::is_move_assignable<devoid<E>>::value,
                                        value_storage_nontrivial_move_assignment<value_storage_select_copy_constructor<T, E>>,
-                                         value_storage_delete_copy_assignment<value_storage_select_copy_constructor<T, E>>>>;
+                                         value_storage_delete_move_assignment<value_storage_select_copy_constructor<T, E>>>>;
```

**Comment by ned14** [comment]
Dear dear, I cannot believe this was never reported until now. Thanks for the BR!

**Comment by ned14** [comment]
Fixed! Thanks for the BR!
