### ISSUE TITLE
Problem with void value type and nontrivial assignment operators

### ISSUE THREAD

**Issue by DiegoBaldassarMilleuno** [ned14/outcome#261]
Hi! Sorry to bother you again, but it seems that there's an edge case broken in the latest fix:
[godbolt.org](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEEgAcpAAOqAqETgwe3r7%2ByanpAiFhkSwxcVyJdpgOGUIETMQEWT5%2BAVU1AnUNBEUR0bEJtvWNzTltwz2hfaUDFQCUtqhexMjsHAD06wDU5gDMocjeWDu7boSxTETEJrvYJhoAgvcPm1uHTAoKWwCSBFsgWySXiitDwyC2CgI6BAIHOxEuJBubkh0JA/GIAHcGugAPpwhHEHH1YCkLahAg3bA7ADsVkery2jMBwNByBAzwZTK8aSMW3wVCosUYqyJAE8kpgTgARLa0ATAWXysmCG50l7bJk/ClmABsW1QEvhV2s1ggcy2DFQmFUqySFN2ateJmpUtVzw521%2BfMwtDYEF%2B5j1hHNzsdGqZxEwBGWDAhUJhYVUBAghFJZjmbvp22drse7rM%2BwYhy8xyRADdqsbbvnC8XS6cCOLMET4YQFJTnkwvEQtlFDP2IGgGJC46iKw5EadyR3dVtxyHac9NV2ewoAF40iwomFpNeYCDznOZh6ayGXME4j5KRoQbewhQ4hSsZtlpFYQ6NiW3tcLUc7vB7kSlIZg67ouhwCy0JwACsvB%2BBwWikKgnBuCalgQksKySnsPCkAQmgQaQEBIGgWC4IQJDkJQND0MwbCcLh/CCCIYjsFIMiCIoKjqAhOi5AYRgoGhNjtI4zgQK4ox%2BNB0jBFMJRlP4Op5GkYmZJ4LQgDJKkFAwvQKQMuq2D6la1BMUladIolmd0%2Bn9HERlniMGk5NpTmTMU9lKQsCiYasnB7AcRzYWYZgIAQBBJAoICbPCGIAHTAIQCDAtysRDgQjAEPFaAsOsYToFI6xLAQuWYOsACc0GCrsZjIPEOrIFQkjIMgkgVVQogVfETBMDqOqSIK8QVcgOpcNB0H9VVXDrDywD0AAtAgmBMFgxDFd2ZXxQgSRJOYZg1kFJbYQ2TYtkwbYdnmjyQsQXgOFs2BcJuS5Mk9Zqap9X3fZ9NwylgVBdrQ9pqpq71DiOT2BvqBDLcQ5o/Uyf3eoDXjA8eYNcBAUO6tDqCw7ECOI19yMA0DIOvYyON6gaFxVlKg4CJDXB4wT8ObnOYjSjDcPxWWXMAFRbAdDpbJG0bELGAuw3g7ai0eoGPJjeOGgSf3YyzuOzvjcNE0juz/ZgqPo4rJ5MgAfu9evEzb3Nk2jFPXWbjJJMQeD85l7JK0y5Kc7Qx4K2qzxno4yCXp8sTJoyd6yziaBJKKcdMwQd01CCL5IlDtw2yBaohxeV6RxA0fxveOIsKgFZJ8OKf3Y46c4q%2BpxZ1SxO58H9Sh%2BH15R3%2BZfx4nV54MAzAN03bgt7bjLtzdncFxHN4l6iscV1XQ8j0wY%2BZyz2dTzPDz52HheL33scp%2B7eBiLQicD9Xt113gW/NzvVL74f3dF0vMJn27ZaX7Q19y6V2bBDWuad6CN23pSLYb855HwXlHMAYAY4PnPn/K%2BN8DSD0%2BMPUeEDx6TyZLA888Ce7F1Pqg3%2B/9AGr2bOvPBGdn7QKIQHR43JQgKjcMtZAABrTAhVuYlTKo3MwMJkDcL4egcsqA8DoFJC3Y879j5RxQUnBO3dcGb3wUiLh1RJEvxgawp4s9U5/GwGYF63sqZmA%2BlPKepMjbkwxm9GxoDHoHW1mza230HHG0ds7dx2MPE6lZrrOx%2BtDZ%2BOcdYlWdNJwMzceY0JhM7aOIdtE9xsSjTxKCYGZJ7Nfq0j9oItmfNBbC1VGLKMMYtjSwQLLSpgdKZbEtjY7x4TfoGxRk402zTXbu0uOwZpvt%2Bb%2B16S6IxSiEHkNUbfUBpjH7aObiLVuiNiFd2UTM0uK9gF3zAfXJZE8Vk50UXAj%2BJ9ZlYI0RvJ%2BRzmG23WfPMhX8y60OuQwyByz7knNNlM55FCWwXwwWozBNcFm3KSdnR5pDP4ArQdQxObz5kPwhcc6F5ze6qPhcC2%2B9CtGMLubvaepySEYuLkgrFVDgVvLxai75%2B9njsN5Lo3h/CLHIyEagNgIixESP4dI2R8iVkko2dMgFNKcE3MOSyyRaLjyESghwWCpB4KIWQhwVClhrAYWWKsHYBYzC8HwrxOYCweEgEkFweKGgKr9Q0NBakkhLVmGgrsXY0hFWSDggRJCnBeDRS4HhAiCw4CwBgIgFAXKkh0FiFRRmLBo30DiMALgXAAg0UysQaKEAog%2BqiKEBoooGK8FymwQQAB5Bg18fVYBYIYeaaxEL4EjDUCs0VeKBFUNUbsaxcLkh9D60EUR4TEFFB4LAPrz4sGLQsKgBhgAKAAGp4EwBictEp4KMVkCxcQ7EmLyCUGoH1uhA0CWMMJfQj9oqQAWAaNS7aFooj%2BqYLVlguDUi2AtAA6lfT9X7rQpyYJ%2BiU6BDCh0/eW3C1lxKSRcn4QNclPIzHKDpNSFlA0pFUhkOyyG9DQYYF0Zy2R4PGXsGpQjHlpiKUDe5dDQxbLyS8lwHyfk2J4UjL2hVMFvUdvVaoBqC0BpbGAK1LYqb4oWIgJqqwlh5H4CuPq3YgatgeATTG4ginmNGuDUREiUb1NxtyomgYKa018DoJm7NuaO35uYKO4tpBS1ZUrdWjttb63iDc3gFtjg20%2ButN2z23BeD9sVYhIdI6x0YEbUat207guzvnUulda6N0Of3Tuti0h91cSPR23QAQz1CVfTYId16zRITtBkB9T6DYvpkxYd9EGoMmQ6H4CSDB3Bwb0IhqjsxUMZDo5h3SOHqOkdMp0cy3WaOtfIxMUb/XaPTfo40Bb5QWO6vYAEFOmBOOQW4yqn1fGBNCZE%2BCcTknpPWDkxRDTewAgqf00mxT6ZtMmrNSAMaEmzDUnGpIDQkgdQVQqo6/QnAvWkGnWYCq8V2rUjMBoHU1INC7AqlwRH77Du8b9bYPQxqtAhvDcREAJUgQEEM09/r/Dbt6Ay6IXd2XZC5Z4ohHbnHSAYnhEkGdYOlU8bVZwct3Yyf6ioFsfjOpBOSGE6Ji7WwpOU7uwWLTQaTW6ZJ8L7sFO1NJtyNTq4uQ6esQkIzzih6Wexd2w5znTBudq8Vcq1VvB1VC8it2UX4uTvS7O2Jq1l3FcvbmG9gnCxlqrQGBVz1vBp3I/itBDQP2Kq1VtRoYauxEhO99Rwf1ePg0fegvEeKFUUeo8kC6gvjqdSJEVbsfnzucf44gvtjghqscC%2Bz6rkPpAKxZoyBaoAA)

The problem arises when `T = void` and `E` has a non-trivial copy or move assignment.
Copy/move construction seems to be fine.

**Comment by DiegoBaldassarMilleuno** [comment]
Alright, that fixed it. Everything is passing on this end.

Props to you for fixing this so quickly! :100:

**Comment by ned14** [comment]
`void` is the bane of all our existences!

Glad it's fixed. Just now need to get it into the upcoming Boost release. Thanks for the BR!
