### ISSUE TITLE
Errors with non-embedded status code

### ISSUE THREAD

**Issue by gix** [ned14/outcome#268]
When setting `OUTCOME_BUNDLE_EMBEDDED_STATUS_CODE` to `OFF`, `find_quickcpplib_library` complains that no `project()` has been called. So this has to be moved further down (not sure if `ensure_git_subrepo` can be moved too).

`include/outcome/experimental/status_result.hpp` also received knowledge about whether system or embedded status code is used to include `system_error2.hpp`. This logic is missing in `coroutine_support.hpp` when including status code's `system_code_from_exception.hpp`.

The only other thing that then fails with vcpkg is that status code headers are put into a `status-code` directory which is missing in its `INTERFACE_SOURCES`.

**Comment by BurningEnlightenment** [comment]
Yeah, I stumbled accross them, but I forgot to upstream the fixes, sorry.

**Comment by ned14** [comment]
status code has been fixed, but Outcome is currently locked for pending Boost release. It should be fixed soon.

**Comment by ned14** [comment]
Boost has had its 1.80 release, you are unlocked to make changes. I just updated status code to trunk, that should enable fixing this bug.
