### ISSUE TITLE
Potentially outdated documentation

### ISSUE THREAD

**Issue by jeromehue** [ned14/outcome#280]
Being new to error handling in C++, I tried to follow the example for the standalone single-header experimental library available at https://ned14.github.io/outcome/experimental/worked-example/.

However, the code snippet from this page :
https://ned14.github.io/outcome/experimental/worked-example/implicit_conversion/ :
```cpp
inline outcome_e::system_code make_status_code(file_io_error v)
{
  return make_status_code_ptr(std::move(v));
}
```
is not compiling, since `make_status_code_ptr()` has been removed from the library.
From what I understand, it has been replaced by some `make_nested_status_code()` function in the status_code repo, but that is not included in the single-header version.

So what will be an equivalent of this example that works with the current version of the library ?

**Comment by ned14** [comment]
Indeed you're right. Sorry about that.

**Comment by ned14** [comment]
Fixed, with correct docs now at https://ned14.github.io/outcome/experimental/worked-example/implicit_conversion/.

Thanks for reporting this issue, I don't know why the CI didn't spot it.
