### ISSUE TITLE
The v2.2.7 tag is missing

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/outcome#287]
There is no [v2.2.7](https://github.com/ned14/outcome/releases/tag/v2.2.7) tag, it seems that you accidentally used the latest all tests passed tag https://github.com/ned14/outcome/releases/tag/all_tests_passed_018620768577911c9b259275a5957525d55ad09a for creating the release

**Comment by ned14** [comment]
Hopefully fixed. Sorry about that, I was on solo childcare when I did the release.

**Comment by BurningEnlightenment** [comment]
Looks good, thanks for the lightning fast response :)

**Comment by ned14** [comment]
I'm at work now, undistracted by small children clamouring for food :)
