### ISSUE TITLE
Error loading embedded GDB pretty printer

### ISSUE THREAD

**Issue by CrustyAuklet** [ned14/outcome#301]
Recently upgraded to the latest version and ran into an issue with the embedded GDB pretty printer.
The error was pretty silent, I had to scroll up to the beginning of my GDB session to see it. I noticed because I was using the python file version before, and after upgrading Outcome and removing the python file my pretty printing went sideways. Embedding the pretty printer is a pretty awesome technique, I wonder if there is a way to test to make sure it loads correctly?

### Environment
**Compiler:** arm-none-eabi-g++ (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009
**GDB:** GNU gdb (GDB; JetBrains IDE bundle; build 200) 14.2

### Details
When loading the program GDB gave me the error:
```
Function(s) Catch will be skipped when stepping.
  File "<string>", line 5
    return gdb.Value(s + '
                         ^
SyntaxError: EOL while scanning string literal
warning: Invalid entry in .debug_gdb_scripts section
```

There are two instances of this in the single header version:
https://github.com/ned14/outcome/blob/a4f6b1b1899632bcdafdd1f078ca49969428e9f6/single-header/outcome-experimental.hpp#L3966
https://github.com/ned14/outcome/blob/a4f6b1b1899632bcdafdd1f078ca49969428e9f6/single-header/outcome-experimental.hpp#L8139

It just needs an extra level of escapes so that the final python code has `\0` in it instead of a literal null byte in the data.
```
".ascii \"    return gdb.Value(s + '\\\\0').cast(gdb.lookup_type('char').pointer())\\n\"\n" 
```

**Comment by ned14** [comment]
Thanks for reporting this, and sorry for the delay in reply (I was on annual leave). I'll try to get a fix for this in tonight.

**Comment by ned14** [comment]
This should now be fixed. Thanks to @k3DW for the starter Python script, and thank you for reporting it.

**Comment by k3DW** [comment]
> This should now be fixed. Thanks to @k3DW for the starter Python script, and thank you for reporting it.

Ha, that script isn't public yet! I'm glad it worked for you, and thanks for the shoutout 🙂
