### ISSUE TITLE
expected<T> incorrectly requires that T be default-constructible

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#43]
The following fails to compile:

```c++
struct Date              // no default constructor
{                        // (no default date exists)
  explicit Date(int) {}
};

out::expected<Date> fun ()
{
  return Date{1};        // this fails to compile
}
```

It fires a `static_assert`:
```
"value_type must be default constructible (LEWG Expected requirement)"
```

This is incorrect, as per [p0323r1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0323r1.pdf) (see section X.Z.4.1 in the proposed wording) `is_default_constructible` is only required when someone triggers the default constructor of `expected<T>`. Otherwise `expected` would be not usable for any type without default constructor.

**Comment by ned14** [comment]
Blocked by issue #16

**Comment by ned14** [comment]
Expected removed in v2
