### ISSUE TITLE
Add set_error_from_exception(std::exception const& e, std::error_code_extended not_matched = std::errc::resource_unavailable_try_again)

### ISSUE THREAD

**Issue by ned14** [ned14/outcome#50]
Also this overload:
-  bool set_error_from_exception(std::exception_ptr const& e)

As the CATCH_ALL macro confers no benefit, replace implementation with this API or replace entire macro.

Add FAQ entry on how the throw keyword is never elided by any compiler

**Comment by pdimov** [comment]
It's better to also give the exception to the second overload because you typically already have it, so this saves a rethrow inside the function.

```
try
{
    r.set_value( throwing_api(args...) );
}
catch( std:::exception const & e )
{
    r.set_error_from_exception( e, std::current_exception() );
}
catch( ... ) // if you like this sort of stuff
{
    r.set_exception( std::current_exception() );
}
```
