### ISSUE TITLE
Single-header implementation doe not compile

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#57]
Outcome provides a single-header implementation in [https://github.com/ned14/outcome/blob/develop/single-header/outcome.hpp].
It is my expectation that if I just copy and paste the contents of this file into Wandbox, append `main(){}`, this will compile. But it does not neither on Clang nor on GCC: 
[https://wandbox.org/permlink/YHxXzxlPBprQgPjb].

**Comment by ned14** [comment]
It works fine on godbolt with the default gcc 7.1 (I did test it there before uploading).

But interestingly does not work with gcc 6.3, nor clang 4.0 with similar errors to wandbox. So I guess this is a bug.

**Comment by ned14** [comment]
I've discovered the cause. The requisite macros are only being defined if -fconcepts is on. This is why I didn't spot the problem sooner. Fix is coming shortly, thanks for the report.
