### ISSUE TITLE
result<NonMovable> supported?

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#59]
In c++17 you can return by value a non-movable object, like `std::mutex`. I need a clear statement whether returning these types in `result<>` is intended to be supported. Currently OUTCOME_TRY moves objects around.

**Comment by ned14** [comment]
I have refactored OUTCOME_TRY to use decltype(auto) and use forwarding of references instead of moving, but it's part of my WIP `success_type` and `failure_type` refactor which isn't finished yet. So consider the answer to this is yes, and it'll hit develop branch probably tomorrow.

**Comment by ned14** [comment]
FYI there is now a dedicated unit test making sure OUTCOME_TRY never copies nor moves.

**Comment by akrzemi1** [comment]
Is there any good reason to use `decltype(auto)` instead of `auto&&`? An automatic reference extends the lifetime of a temporary anyway. The latter syntax has an advantage that it allows returning non-moveable objects by value even in C++11.

**Comment by ned14** [comment]
Welcome back from your holidays! This library definitely cannot ever work in C++11. The decltype(auto) I thought simply binds to whatever reference is fed in, so it is surely the exactly correct thing to use?

**Comment by akrzemi1** [comment]
I mentioned C++11, but it also applies to C++14.

```c++
X fun();
decltype(auto) r = (fun());
```
This deduces type `X` for variable `r` -- not a reference: a value. [Check here](https://wandbox.org/permlink/eWXvFNU66wyaqeLS).

And immediately stops working for non-moveable types. In contrast, the following deduces the correct reference type for `r`:

```c++
auto&& r = (fun());
```

**Comment by ned14** [comment]
I do see what you mean.

Can you tell me then how come https://github.com/ned14/outcome/blob/develop/test/tests/issue0059.cpp works? Is the test wrong?

**Comment by akrzemi1** [comment]
It is the way `decltype(auto)` is defined:

```c++
X get_x();
X x;

decltype(x) == X;
decltype((x)) == X&; // your case
decltype(get_x()) == X;
decltype((get_x())) == X;
```

If you test function return value with `OUTCOME_TRY`, it does no longer work: https://wandbox.org/permlink/CMIvGhxTAplpAwyj

**Comment by ned14** [comment]
Ok, thanks to your example I got my test to be testing the correct thing. Is now fixed. Thanks!
