### ISSUE TITLE
Any updates on MSVC support?

### ISSUE THREAD

**Issue by garyng** [ned14/outcome#63]
Is the library working the the latest 2017.3 update?

Thanks 😄

**Comment by ned14** [comment]
Microsoft actually added Outcome to the MSVC test suite which was very kind of them.

It's working well on MSVC trunk, but not 15.3. They say 15.5 will when when that compiler lands public.

Until then you can either install trunk MSVC from nuget, or use trunk clang llvm 6.0 for Windows which is what I'm using. You can find prebuilt nightly binaries for Windows on the llvm website.

**Comment by ned14** [comment]
MSVC is now supported in master branch. I was supplied with a set of patches to workaround the parser bug. So should now be good in all VS2017's. Let me know if it isn't.
