### ISSUE TITLE
Outcome failed to build with error C3861: 'BOOST_CHECK_EQUAL': identifier not found. 

### ISSUE THREAD

**Issue by KarenHuang2016** [ned14/outcome#66]
We build Azure_iot_sdk_c with Visual studio 2017 compiler on Windows Server 2016, but it failed with with  error C3861: 'BOOST_CHECK_EQUAL': identifier not found. This issue should be caused by revision 7153efb. In revision 7153efb, “BOOST_CHECK_EQ” is changed to “BOOST_CHECK_EQUAL”. Could you help have a look about this issue? Thanks in advance!

**Failures**:
 D:\Outcome\src\test\expected-pass.cpp(419): error **C3861**: **'BOOST_CHECK_EQUAL': identifier not found [D:\Outcome\build_x86\outcome_hl--expected-pass.vcxproj]**
         D:\Outcome\src\test\expected-pass.cpp(420): error C3861: 'BOOST_CHECK_EQUAL': identifier not found [D:\Outcome\build_x86\outcome_hl--expected-pass.vcxproj]
         D:\Outcome\src\test\expected-pass.cpp(431): error C3861: 'BOOST_CHECK_EQUAL': identifier not found [D:\Outcome\build_x86\outcome_hl--expected-pass.vcxproj]
......
 D:\Outcome\src\test\expected-pass.cpp(1024): error C3861: 'BOOST_CHECK_EQUAL': identifier not found [D:\Outcome\build_x86\outcome_hl--expected-pass.vcxproj]
         D:\Outcome\src\test\expected-pass.cpp(1025): error C3861: 'BOOST_CHECK_EQUAL': identifier not found [D:\Outcome\build_x86\outcome_hl--expected-pass.vcxproj]

**Repro steps:**
1. Open VS2017 x86 Native tools command tool
2. git clone --recursive http://www.github.com/azure/azure-iot-sdk-c D:\Outcome\src
3. cd D:\Outcome
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src\
6. msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild

**Comment by ned14** [comment]
I tried your repro, but it builds fine for me here. Furthermore, I can see no copy of Outcome brought in by your git clone --recursive. Did you mean maybe a different branch than master branch?

**Comment by KarenHuang2016** [comment]
@ned14, I still can repro this issue on master branch. I attached our build log. Could you please take a look? Thank you so much!
[Outcome_x86_build.log](https://github.com/ned14/outcome/files/1370928/Outcome_x86_build.log)

**Comment by KarenHuang2016** [comment]
In Outcome source code, header file "quickcpplib/include/boost/test/unit_test.hpp" defined 'BOOST_CHECK_EQ'. There is no definition for 'BOOST_CHECK_EQUAL'. 

In expected-pass.cpp file line 32, If I change the code like below. It build fine.
From
**#define BOOST_TEST_EQ(a, b) BOOST_CHECK_EQUAL((a), (b))**
to
**#define BOOST_TEST_EQ(a, b) BOOST_CHECK_EQ((a), (b))**

Does the boost header file unit_test.hpp need to be updated?

**Comment by ned14** [comment]
Karen, after you pull latest from the outcome git repo, are you running `git submodule update --init --recursive` afterwards?

If you do not do this, the git subrepos remain on the original checkouts, and thus the subrepos become mismatched to the master repo.

**Comment by KarenHuang2016** [comment]
@ned14, you are right. After I running  "git submodule update --init --recursive", Outcome build fine. Thank you so much :)

**Comment by ned14** [comment]
Glad you got it working Karen. May I ask why you are using Outcome? I found that a great surprise given it only started working on Visual Studio very recently thanks to a set of patches I was given.

**Comment by KarenHuang2016** [comment]
Yes, we start building Outcome with VS on August 2017. We are testing VC++ compiler using Outcome source code.
