### ISSUE TITLE
git clone fails

### ISSUE THREAD

**Issue by Red-Portal** [ned14/outcome#70]
```sh
error: Server does not allow request for unadvertised object 755b7f9e5c5fab7dda44876e6f16f353134f2e97
Fetched in submodule path 'third_party/outcome/doc/html', but it did not contain 755b7f9e5c5fab7dda44876e6f16f353134f2e97. Direct fetching of that commit failed.
Failed to recurse into submodule path 'third_party/outcome'
```

```git submodule foreach git reset --hard```

somewhat let's me build with other projects with outcome,
but the error doesn't go away

**Comment by ned14** [comment]
We had problems with getting the documentation to build by github pages, so we threw away the gh-pages branch entirely. You will need to enter doc/html and do a force git fetch. Alternatively simply wipe the entire outcome repo, including any .git directory, and reclone from scratch. Sorry for the inconvenience.

**Comment by Red-Portal** [comment]
@ned14  I kindda found the solution by using your boost-ed version instead of this repo. Is there any progress on officially entering boost?

**Comment by ned14** [comment]
We think the second peer review will be end of January.

**Comment by Red-Portal** [comment]
Ok I'll be looking into that. Thanks for your great contribution!
