### ISSUE TITLE
Too powerful implicit conversion

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#71]
The converting constructor for `result<T>` (and probably for `outcome`) is too powerful: it is available even for types `X` for which `T` only provides an explicit constructor. The following for instance compiles and crashes:

```c++
#include "outcome.hpp"
#include <memory>

namespace out = OUTCOME_V2_NAMESPACE;

int main()
{
    int i = 1;
    int * p = &i;
    out::result<std::unique_ptr<int>> r = p;
}
``` 

`std::unique_ptr` does not convert from a raw pointer exactly to avoid bugs like this. But `result` promotes this to an implicit conversion. Here is the life example: https://wandbox.org/permlink/53Vn1mnWSaLCjZTx

Normally, what you want to do in this case is to provide a "conditionally" explicit converting constructor. I.e., you provide two: explicit and converting, and them disable them with SFINAE tricks based on `std::is_convertible<X, T>`.

**Comment by ned14** [comment]
This is actually a bug I already knew about, and had forgotten about. Thanks for reminding me! Note that my fix is actually to only implicitly construct from convertible things, not constructible things. The explicit constructors continue to use is_constructible.

**Comment by ned14** [comment]
Fixed in develop branch. Thanks for the report.
