### ISSUE TITLE
extern usage in error_code_registration.cpp is not clear enough

### ISSUE THREAD

**Issue by Talkless** [ned14/outcome#74]
[Custom error codes](https://ned14.github.io/outcome/tutorial/error_code/) example contains this definition [0]:
```
extern const detail::ConversionErrc_category &ConversionErrc_category()
{
  static detail::ConversionErrc_category c;
  return c;
}
```

Does this `extern` is there to give a hint to move this function into `.cpp` file? Because currently, using this example inside `MyError.h` produces duplicate symbols while linking, if error code is used included in multiple places.

For C++17, maybe `static detail::ConversionErrc_category` could be inline variable placed inside caterogy class, but in this case, I am not sure how or why this `extern` should work.

[0] https://github.com/ned14/outcome/blob/025147e4fad16b27d060054c10a6d020d1d4e323/doc/src/snippets/error_code_registration.cpp#L66

**Comment by akrzemi1** [comment]
I think it was supposed to read `inline` instead of `extern`.

**Comment by ned14** [comment]
Yep, should be both inline and extern in fact. I'll fix it once back from Florida in the new year. Thanks for spotting it and merry Christmas!

**Comment by Talkless** [comment]
It _can_ be both? OK...

Thanks and good holiday for you too!

**Comment by ned14** [comment]
Does the new wording at https://ned14.github.io/outcome/tutorial/error_code/ look good to you?

**Comment by Talkless** [comment]
Sentence 
> But for this example use a global instance but with inline linkage so multiple definitions do not collide.

Is a little hard to understand due to two `but`'s, but it's OK I guess.
