### ISSUE TITLE
FAQ regarding performance is possibly lacking info

### ISSUE THREAD

**Issue by do-m-en** [ned14/outcome#78]
https://ned14.github.io/outcome/faq/#what-kind-of-performance-benefits-will-using-outcome-in-my-code-bring

I either don't know how to read the graph or the graph is missing a vital info and is thus misleading and semi useful at best.

Consider this use case:

I parse an XML file and write a function that returns a string from a node on a certain XPath and either I believe that a certain node is mandatory (an exception should be thrown if it is missing) or optional (a value should optionally be returned) so I write two function signatures:
std::string get_node_string(std::string_view simple_xpath); // mandatory element - throws if element is missing
std::optional<std::string> get_node_string_optional(std::string_veiw simple_xpath); // optional element

In most cases the node will exist and in most cases I expect the node to be mandatory. In rare cases a node is optional and in even rarer cases a XML file will be missing a mandatory node (expect that this is so rare that for performance purposes I either don't validate XML by schema or the XML is structured so that not all relations can be validated by an XML schema - relations between separate nodes).

In cases where a mandatory node is missing I want to throw an exception as the transaction has to be rolled back and the code flow has to resume quite a few functions up so I don't want to pollute the code by returning n levels up (if this is not the "right" way to structure the code consider it being a legacy code that should not be changed but has a deep call depth).

Consider this being a case where the regular flow is supposed to be fast and for exceptional cases I can take a bit more time so I don't even care if an exception takes longer to propagate than returning result containing an error code.

The provided graph shows me that returning an int/error_code/result is faster than throwing an exception but it doesn't show me how much it costs me to check if result contains a valid object or an error before processing/throwing the result - and this is what interests me far more than "in case of an error exception throw is allot more expensive".

Could the graph be extended/a new graph added that shows me how much overhead is on the regular path due to use of result with a single function signature (once for mandatory element where result is always considered to be valid and once for optional element which is considered to either contain an element or the result is ignored and the processing moves on without using the error code) compared to using two function signatures as described above without ever throwing an exception for mandatory element (and calling the non-throwing function for optional element)  - always returning correct result as exceptions are so rare that I can ignore their overhead in such conditions?

**Comment by ned14** [comment]
I think I see what you mean. The benchmark for the value and error cases is always checking for the returned result to be valued or errored. The exception throw case is always an exception throw. What is missing is the "null case" where we never check for valued nor errored. In other words you want an extra column on the graph for the "success" case?

Please do say if the above is a correct analysis of your reported issue.

**Comment by do-m-en** [comment]
Sorry for my poor explanation skills... Actually two cases:
- The overhead that you pay for during success case (where exception is never thrown) compared to always returning result<...> and checking for success/fail,
- The overhead that you pay for throwing the exception immediately at the exception creation site compared to returning outcome<...> and checking for error state before throwing the exception.

I'm guessing that both cases produce negligible overhead but my guessing is surprisingly often wrong and since the graph already exists in the docs it would be a great place to refer people to when such questions inevitably arise.

**Comment by ned14** [comment]
The first case I agree with. Good catch, thank you.

The second case I don't think useful. Throwing and catching an exception is so expensive that it will utterly dominate everything else. I could do a loop counting to 10,000 and the exception throw and catch would still be dominant. Therefore a simple compare and branch won't be statistically significant in your second case.

I'll fix the first case soon. Thanks for the report.

**Comment by ned14** [comment]
Just pushed finished revised FAQ with new graph with null case. Thanks for the BR.
