### ISSUE TITLE
Could you get rid of all the references to detail in the documentation?

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#82]
The documentation makes a lot of references to detail folder and detail namespace. These are implementation details.

Could you get rid of all the references to detail in the documentation?

**Comment by akrzemi1** [comment]
Also, in the index page (https://ned14.github.io/outcome/reference/) we get documentation for macros like:

- `OUTCOME_TRY_GLUE`
- `OUTCOME_TRY_GLUE2`
- `OUTCOME_TRY2`
- `OUTCOME_TRYV2`

which are also only implementation details. Maybe there is a way to annotate them in the sources, that they should be skipped when producing documentation?

**Comment by ned14** [comment]
> Could you get rid of all the references to detail in the documentation?

@foonathan [is on the problem](https://github.com/foonathan/standardese/issues/94)

Regarding the macros, Jonathan has added an `\exclude` for me that I have yet to try. I'm on it.

**Comment by viboes** [comment]
What about the detail folders and namespaces?

**Comment by viboes** [comment]
Sorry I missed the reference to standardese issue

**Comment by ned14** [comment]
Yeah standardese is currently not blacklisting the detail directory like I'm telling it to do. I may be using it wrong of course.

**Comment by foonathan** [comment]
This is done now (except for the unexposed entities, working on that).

**Comment by ned14** [comment]
Alas no, if you search the generated docs, detail still appears in places.

**Comment by foonathan** [comment]
Yes, but those are due to #89.

**Comment by ned14** [comment]
Let's track this via #75 instead
