### ISSUE TITLE
all capital letters for section and header files  names

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#85]
While we would expect the section/headers to be
outcome<R, S, P>
Header file outcome.hpp

The html file should this on all capital letters
https://ned14.github.io/outcome/reference/outcome/

**Comment by ned14** [comment]
I don't understand what you mean. The section headers are indeed all caps. What do you want changed?

**Comment by akrzemi1** [comment]
Identifiers in C++ and file names in unix-like systems are case sensitive. When you use capital letters, you are in fact using different names than intended. I guess the suggestion is not to use capital letters when referring to lower-case C++ identifiers and file names.

**Comment by viboes** [comment]
@akrzemi1  Right.

**Comment by ned14** [comment]
Is it really that unclear that it's a stylised header font?

**Comment by viboes** [comment]
No, it is clear for me as I'm used to lower case file names, but it could be confusing for other users,  and when you copy paste it it is in lower case. 

I would prefer to see `boost/outcome/xxx.hpp` somewhere.

Up to you.

**Comment by ned14** [comment]
Let's see how the reviewers take it. They'll already be seeing lots of new tech in these docs, they may become filled with happiness, or hate the lot of it. Thanks for raising the potential issue though, never occurred to me.

**Comment by viboes** [comment]
why do you close the issue then?

**Comment by ned14** [comment]
I don't consider it an issue until a consensus during the peer review makes it so.
