### ISSUE TITLE
noexcept('hidden'); not described for some operations

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#86]
In particular for:

https://ned14.github.io/outcome/reference/outcome/#standardese-outcome_v2_xxx::operator==%3CT,U,V,R,S,P,N,%3E(result%3CT,U,V%3Econst&,outcome%3CR,S,P,N%3Econst&)

**Comment by viboes** [comment]
I mean that I expect the expression that is `hidden`. The standard use to use something like 

*Remarks*: The expression inside `noexcept` is equivalent to: ...

**Comment by akrzemi1** [comment]
I think the quoted definition should read:
```c++
template <class T, class U, class V, class R, class S, class P, class N>
constexpr bool operator==(result<T, U, V> const& a, outcome<R, S, P, N> const& b) noexcept(noexcept(b == a));
```
*Effects:* equivalent to `b == a`.
*Remarks:* This function shall not participate in overload resolution unless `b == a` is a valid expression.

The effects clause already implies that `a == b` throws whatever `b == a` throws. But what an operator potentially throws is not the same as if it is declared to throw or not, therefore it should be spelled out explicitly.

**Comment by viboes** [comment]
This will be okay for me.

**Comment by ned14** [comment]
Alas Standardese either quotes noexcept expressions in full, or they are 'hidden'. One or the other.

There is also no `\remarks` markup available. @foonathan what do you think?

**Comment by foonathan** [comment]
About \remarks? Or a more selective noexcept?

**Comment by foonathan** [comment]
About \remarks? Or a more selective noexcept?

**Comment by foonathan** [comment]
About \remarks? Or a more selective noexcept?

**Comment by foonathan** [comment]
About \remarks? Or a more selective noexcept?

**Comment by akrzemi1** [comment]
Another convention in the C++ Standard is to leave `noexcept` with a placeholder in function signature, and then describe it in the remarks:

```c++
template <class T, class U, class V, class R, class S, class P, class N>
constexpr bool operator==(result<T, U, V> const& a, outcome<R, S, P, N> const& b) noexcept('hidden');
```
Effects: equivalent to b == a.
Remarks: This function shall not participate in overload resolution unless b == a is a valid expression. **The expression inside `noexcept` is equivalent to `noexcept(b == a)`.**

----
But with *Remarks* section also missing I do not know how you can express the interface of your functions.

**Comment by akrzemi1** [comment]
I would say that the support for *Remarks* is the minimum.

**Comment by foonathan** [comment]
I have remarks already: https://github.com/foonathan/standardese/blob/develop/include/standardese/markup/doc_section.hpp#L31

**Comment by ned14** [comment]
Ok, let me see what I can do on this.

**Comment by ned14** [comment]
I've improved the documentation for the operator== etc specifically, but I have not gone through every single function and expanded its *Throws:* clause with an additional *Remarks:* clause with the noexcept calculation. Partially this is because *Throws:* already tells you, partially it is because I think we can get Standardese to extract this automatically in the future. But the main reason is lack of time before code freeze on Wednesday, and there are more urgent matters to fix. But thanks for the report, and feel free to raise it again during the review.
