### ISSUE TITLE
It is weird that all the headers are not in folder <boost/outcome>

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#87]

**Comment by ned14** [comment]
Do you mean the header files, or the source files, or something else? We do follow the standard Boost layout conventions.

**Comment by viboes** [comment]
The public headers, in the documentation.

When I look at https://ned14.github.io/outcome/reference/result/

I expect to have the path to the file. BTW it is boos/outcome/result.hpp, that is the path the user should use.

**Comment by ned14** [comment]
You're not looking at the Boost documentation, you're looking at the standalone documentation. The reason that you can't look at the Boost documentation is that how we can generate Boost format docs from the current docs is an open question that I cannot answer without substantial dialogue and negotiation with the Boost maintenance team, and depending on their decisions, that chooses how we generate the Boost documentation.

I'll explain all this when the peer review begins, and I appreciate it is not optimal. Bleeding edge tooling comes with costs.

**Comment by viboes** [comment]
Niall, we are not looking for Bleeding edge tooling, but for good documentation :)
If the tool inhibit you from having clear documentation you should change the tool.
This is why I have often preferred to write them manually.

**Comment by ned14** [comment]
Sure, but that approach would not help a sorely needed replacement for doxygen to reach maturity.

This approach is risky for Outcome, it may get rejected due to deficiencies in Standardese. But my hope is that the Boost community will be tolerant due to wanting to also support the maturation of a doxygen replacement.

**Comment by ned14** [comment]
Fixed after manual rewrite of reference docs.
