### ISSUE TITLE
Template parameters in 

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#88]
In https://ned14.github.io/outcome/reference/result/#template-parameters, all the template parameters don't follow the same style

```
Template parameters

    NoValuePolicy — Policy on how to interpret type S when a wide observation of a not present value occurs.

Template parameter R

class R
```

**Comment by ned14** [comment]
Yes you're right. Standardese parsing bug. @foonathan.

**Comment by foonathan** [comment]
Actually, no this is not a parsing bug: If a template parameter only has brief documentation, then it will be shown in an inline list.

However, if you meant that the entire `NoValuePolicy defaults to a policy selected according to the characteristics of type S` section should be part of the `tparam` for `NoValuePolicy`, then that is a feature request to allow more than one paragraph for a `tparam`.

**Comment by ned14** [comment]
Ahhhh okay. This I can fix now. Thanks Jonathan.
