### ISSUE TITLE
Why Outcome doesn't support heterogeneous equality operations

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#90]
I see 

```
template <class T>
constexpr result(T&& t) noexcept('hidden');
```

What about doing as the standard does with EXPLICITstd::pair)?

Could we compare `result<T>` and `result<U>`?

**Comment by ned14** [comment]
For some `result<T, E>`, a `result<X, Y>` will *explicitly* convert from it if X is constructible from T and Y is constructible from E (or E is void).

Comparison of `result<T>` and `result<U>` should work just fine. My own code does it, and here it is working on wandbox: https://wandbox.org/permlink/ViQAOLbYbvF6iAoE

**Comment by viboes** [comment]
It is not clear from the documentation

**Comment by ned14** [comment]
That's because none of the comparison operators are appeared. I'm working on it.
