### ISSUE TITLE
Where is described `result_or_outcome`?

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#91]

**Comment by ned14** [comment]
Excellent question @foonathan. I can find no "result_or_outcome" anywhere in my code!

**Comment by foonathan** [comment]
Wait, are you saying standardese has generated the "result_or_outcome" on it's own or is it just not documented?

**Comment by viboes** [comment]
See https://ned14.github.io/outcome/reference/result/#standardese-outcome_v2_xxx::result%3CR,S,NoValuePolicy%3E

**Comment by foonathan** [comment]
And there is nothing called `result_or_outcome` in any code?

**Comment by ned14** [comment]
I discovered the cause: my fault. My python script is injecting result_or_outcome. Apologies!

**Comment by viboes** [comment]
I believe that you have fixed this, isn't it?

**Comment by ned14** [comment]
Issue #94 tracks the ultimate fix.
