### ISSUE TITLE
Why the namespace is outcome_v2_xxx?

### ISSUE THREAD

**Issue by viboes** [ned14/outcome#92]

**Comment by ned14** [comment]
Explained first page of the tutorial https://ned14.github.io/outcome/tutorial/result/#outcome-2-0-namespace

**Comment by viboes** [comment]
In this case the reference documentation should use `OUTCOME_V2_NAMESPACE` instead.

**Comment by ned14** [comment]
That would be quite ugly. Let's see what the reviewers think.

**Comment by viboes** [comment]
I don't see any advantage to hide in the documentation the real interface.
