### ISSUE TITLE
operator conversions on E type cause TRY to fail

### ISSUE THREAD

**Issue by ned14** [ned14/outcome#95]
Repro:

```c++
#include "outcome.hpp"
#include <iostream>
#include <type_traits>
#include <system_error>
#include <sstream>

namespace out = OUTCOME_V2_NAMESPACE;

struct E {};
//struct F : E {};
struct F { operator E() const { return E{}; } };

out::result<int, F> f() { return F{}; }
out::result<int, E> e() 
{
    OUTCOME_TRY (i, f());
    return i;
}

int main()
{
}
```

**Comment by akrzemi1** [comment]
What does this issue try to describe? The above source code fails, but it was my understanding that the design goal was, "no implicit conversions" in `TRY`. Or is your intention to allow `TRY` to convert from `failure<EC1>` to `result<T, EC2>` when `EC1` is convertible to `EC2`?

**Comment by ned14** [comment]
There are two problems needing fixing:

1. Implicit conversion from failure_type is currently reusing the explicit predicates, which needs to stop.
2. The code is not working when E types don't match.

**Comment by viboes** [comment]
I believe that heterogeneous conversion should be applicable following the EXPLICIT standard way as used in `std::pair`.

We have recently added this in `unexpected`/`expected`.

**Comment by ned14** [comment]
Outcome intentionally doesn't implement the EXPLICIT system from the STL whereby the implicit-explicit semantics are determined at compile time by traits examination. It's rather heavy on compile times and increases stack bloat, though I applaud the cleanup in C++ 17 pair.

We take a simpler approach intended to prevent hidden conversions which almost always requires the compiler to allocate new storage instead of folding storage during inlining. We are always explicit where result types are not identical in copy/move construction. The user must always specifically say they permit result conversion at some point.

We do permit implicit conversion of T or E to result<A, B> where there is no chance of ambiguity. The same rationale had applied to failure<E>, but perhaps this is unsafe. I'll turn my attention to it on the train into work this morning.

**Comment by ned14** [comment]
Fixed

**Comment by akrzemi1** [comment]
What is the effect of this fix? `TRY` will be able to convert from `failure_type<EC1>` to `result<T, EC2>`? 

In the commit, in the test case [(here)](https://github.com/ned14/outcome/commit/d8c72ccb0ee258583f16e3b59595c554fa9a225d#diff-889cd7b265ddd510e22b49bddc7ec630R50), you return failure, but expect a value. That cannot be correct.

**Comment by ned14** [comment]
Yeah the source didn't compile either. Rush job on the train to work this morning. Should be better now.
