### ISSUE TITLE
Possible issue with Google Mock library?

### ISSUE THREAD

**Issue by nickaleks** [ned14/outcome#96]
My team is trying to use outcome library for error handling in some parts of our project. We used nonstd::optional, but needed error information. but this line below causes compilation error and we are not sure where the issue is:
```
MOCK_METHOD1(getAccountRoles,
                   outcome::result<std::vector<std::string>>(
                       const std::string &account_id));
```
The error is related to << operator, and seems to originate from your library. This issue does not arise when we do a similar thing but the function returns result with type such as std::string, which can be printed to iostream. This leads me to believe that the issue is in the interaction with your library with Google Mocks.
I am not completely sure, and it would be great if you could look at the compiler output and tell me whether or not the issue is in your library and how it can be fixed. Below is the output of Clang.
[error.txt](https://github.com/ned14/outcome/files/1621855/error.txt)

**Comment by ned14** [comment]
Literally a fix just went in for that this morning. Try develop branch.

Note you ought to use `print()` instead of `operator<<`, it produces much more human readable output.

Let me know if develop branch fixes things for you.

**Comment by nickaleks** [comment]
Sadly this fix does not resolve my issue, the only solution that has worked is to exclude iostream_support.hpp from includes in outcome.hpp

**Comment by ned14** [comment]
Can you post the compiler error for the case with develop branch please? It may look similar to before, but it will be different. The change which went in now disables operator<< if either T or E does not implement it. In your use case, std::vector won't implement it, so Outcome's operator<< should self disable. If this is not working correctly, it would be very useful to know.

**Comment by akrzemi1** [comment]
"Disables" in the sense that `enable_if` or concepts will be able to detect it? Ot in the sense that it gets invoked and then triggers hard compiler error?

**Comment by ned14** [comment]
The former. GMock may still try to use it of course, but that's what I want to find out.

**Comment by akrzemi1** [comment]
GTest (and GMock, I guess) has a "fallback strategy". If the type provides "operator >>" it uses it for messages. If the type does not provide the operator it falls back to printing binary data. This works out of the box. By a hard static assertion you are breaking this feature.

**Comment by akrzemi1** [comment]
But if you say that you are already doing the enable-if trick, the reason for breakage must be different.

**Comment by ned14** [comment]
As you'll see at https://github.com/ned14/outcome/blob/develop/include/outcome/iostream_support.hpp#L124, as of this morning there are no longer any static asserts. You convinced me to change!

**Comment by nickaleks** [comment]
Here's a cmake log of the build from the develop branch:
[errors.log](https://github.com/ned14/outcome/files/1625712/errors.log)

**Comment by ned14** [comment]
Repro and cause is at https://wandbox.org/permlink/mPUZGz48XpLuqNzk. Should be easy to fix, hopefully tomorrow.

**Comment by ned14** [comment]
Closing assuming it's fixed.
